### ISSUE TITLE
Repurpose cf-typography?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#100]
~~Or at the least we should slap a warning on it that cf-core has replaced the need for it.~~ Done
At some point we should convert this repo into more advanced typographic patterns.

**Comment by himedlooff** [comment]
Status update: this is in progress by @virginiacc :smile:

**Comment by anselmbradford** [comment]
What's the status of this issue?

**Comment by Scotchester** [comment]
I think this is done, in that everything we wanted to move to cf-typography has been moved there. That said, I think that much of the stuff that was moved to cf-typography still remains in the various Less files of cfgov-refresh, from which it needs to be culled.

**Comment by anselmbradford** [comment]
Sounds like this issue should be moved to cfgov-refresh and closed here?

**Comment by Scotchester** [comment]
Agreed.

**Comment by anselmbradford** [comment]
Living on DF-1405 task in Jira!
