### ISSUE TITLE
Deprecate cf-demo

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#101]
It's VERY outdated.

## Delete/update references to cf-demo within cfpb.github.io/capital-framework docs site

- [ ] `_includes/adding-deps-step2.md`
- [ ] `_includes/workflow-intro.md`
- [ ] `cf-demo/index.md`
- [ ] `contributing/status.md`
- [ ] **Then delete the cf-demo repo**

**Comment by contolini** [comment]
@Scotchester The Jekyll files listed above are no longer used, correct? Should we just delete the files rather than removing references to cf-demo in them?

**Comment by Scotchester** [comment]
Yes. See https://github.com/cfpb/capital-framework/pull/171#issuecomment-108122836.

**Comment by Scotchester** [comment]
Don't delete `status.md`, though. I hope to revive that and make it useful somehow.
