### ISSUE TITLE
Run qUnit tests in multiple browsers

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#104]
Via [Saucelabs and Grunt](https://saucelabs.com/javascript/qunit)?

**Comment by contolini** [comment]
Related to your comment on [#155](https://github.com/cfpb/capital-framework/issues/155#issuecomment-94969000).

**Comment by contolini** [comment]
@anselmbradford I'll be asking you for help with this.

**Comment by anselmbradford** [comment]
@contolini :metal:

**Comment by contolini** [comment]
Given that there's only one component with JS tests, the bang-to-buck ratio is pretty low. Moving this to v1.1.

**Comment by anselmbradford** [comment]
Work done in this PR on sauce tunnel could be brought in https://github.com/cfpb/cfgov-refresh/pull/3040

**Comment by anselmbradford** [comment]
Related to https://github.com/cfpb/capital-framework/issues/194

**Comment by jimmynotjim** [comment]
qUnit has been replaced with Jest, browser tests should be run in browsers, closing in favor of #194
