### ISSUE TITLE
Are there better ways to communicate updates to capital framework to people who don't "watch" the repositories

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#111]

**Comment by himedlooff** [comment]
Since https://github.com/cfpb/capital-framework/issues/115 forces more attention on the design manual maybe this isn't such a big deal anymore?

**Comment by KimberlyMunoz** [comment]
I talked with @Scotchester. We narrowed down the scope of the problem to be that we need a way for people in the Bureau who don't follow the repo to be aware of fixes and changes to the design manual that have made it to Capital Framework. 

> From my experience asking the question "Have you installed the latest update to that component?" a lot when helping someone troubleshoot a CF issue, I don't have confidence that people are really keeping up awareness."

**Comment by KimberlyMunoz** [comment]
The release process in FEWD seems to take care of the issue internally.
