### ISSUE TITLE
More enforcement of testing

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#113]
We have a checklist of tests: http://cfpb.github.io/capital-framework/contributing/testing-snippet.html but we don't enforce it very much. We should be more strict about it.

**Comment by himedlooff** [comment]
Maybe to close this one out we should browser test the current version of the zip.

**Comment by himedlooff** [comment]
Moving this to the 1.0 milestone.

**Comment by contolini** [comment]
Related to [#155](https://github.com/cfpb/capital-framework/issues/155#issuecomment-94969000).

**Comment by anselmbradford** [comment]
Related to https://github.com/cfpb/front-end/pull/37

**Comment by contolini** [comment]
The proper solution here is automated visual regression testing which is scheduled for v1.1.

**Comment by anselmbradford** [comment]
Visual regression testing issue https://github.com/cfpb/capital-framework/issues/19

**Comment by anselmbradford** [comment]
Closing this in favor of the linked related issues.
