### ISSUE TITLE
CDN for Captial Framework

### ISSUE THREAD

**Issue by awolfe76** [cfpb/capital-framework#124]
Just wanted to gauge the interest in having the framework be available over a URL, like a CDN.

This would allow anyone, or any team, to simply include the Framework in their project by doing something like:

```
<link rel="stylesheet" href="https://cdn.cfpb.gov/cf-framework/x.x.x/cf.min.css">
```
and/or
```
<script src="https://cdn.cfpb.gov/cf-framework/x.x.x/cf.min.js"></script>
```

This could help people/teams who want to use the framework quickly, it removes the need to build it themselves. Maybe really useful for prototyping.

The URL pattern also allows for several versions to be hosted. Governance could be created around the number of versions we would be ok with (requiring sites/apps to update at some point to prevent getting to out of sync). Some analytics around it would be really useful in determining who is using what version to help communicate the need to upgrade.

**Comment by himedlooff** [comment]
Also, Capital Framework is constantly evolving and the CDN would constantly be lagging behind. That could be frustrating. Imagine there's an issue with cf-buttons and you make a pr and fix it. You'd then have to wait until it gets merged into the compiled zip and pushed to the CDN. It's faster to rerun bower install to pull in the updates you made. You can even point to your fork of cf-buttons if you can't wait for your pr to get reviewed and merged. This flexibility is pretty important.

**Comment by himedlooff** [comment]
And to clarify, I like the idea! I have no idea how one would implement it but I think it would be a good thing to provide, especially once the framework is a little more stable.

**Comment by awolfe76** [comment]
I definitely have a few thoughts on how to handle some of those problems. I was thinking the CDN would be mostly (if not entirely) for internal CFPB use; built with our branding/colors. So anyone building a site/app here could simply do the includes and go. We could provide one for external users with a different branding but not sure if it's worth it, yet anyway.

I can go over some more thoughts here but maybe sometime from the 25th - 30th we can all get together for a bit? Would be great to meet you all anyway!

**Comment by himedlooff** [comment]
Chatting in person sounds great :boom:

**Comment by contolini** [comment]
This sounds like a great thing to launch with a 1.0.0 release.

**Comment by contolini** [comment]
CDNJS accepts PRs: https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library

**Comment by contolini** [comment]
Bumping this to v1.1 due to amount of work it would involve.

**Comment by jimmynotjim** [comment]
Is this still a concern? I think every newer project has moved to npm installation and packaging with project code. Speak now or stay closed forever.
