### ISSUE TITLE
Add a section on actual usage to the Getting Started page

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#127]
Currently, once the user finishes the scaffolding process, they're sorta left high and dry as to our recommended norms for actually using the codebase. It's left to them to wade through the codebase to glean an understanding of things like "Where should I put my project's Less?"

Let's add a "Working with the framework" section to the Getting Started page.

**Comment by awolfe76** [comment]
+1

After @Scotchester pointed me in the right direction this was pretty straightforward:
- Create your custom .less file(s) in /src/static/css
- import those into main.less (in that same directory)
- you should be good when you build

Seems like a nice, clean way of doing it. You don't have to mess with the Gruntfile, which is where I started. I did get it working but it was a bit more 'messy'.

Thanks for the help @Scotchester!

**Comment by ascott1** [comment]
@Scotchester or @awolfe76 since you both just worked through this, would one of you want to add this documentation?

**Comment by Scotchester** [comment]
I'm certainly happy to help with that, but not sure how soon I can get to it... @awolfe76 if you can take a crack at it, I'll gladly review!

**Comment by awolfe76** [comment]
Same here on time, but I'll do it. Would be good figure out what's going on that side of things too.

**Comment by ascott1** [comment]
TEAMWORK. I like it. 

![http://media3.giphy.com/media/WKdPOVCG5LPaM/giphy.gif](http://media3.giphy.com/media/WKdPOVCG5LPaM/giphy.gif)

**Comment by himedlooff** [comment]
I started this at: https://github.com/cfpb/capital-framework/blob/gh-pages/getting-started/index.md

**Comment by himedlooff** [comment]
If there is additional information you'd like to add please add it, but it's a good start at least.
