### ISSUE TITLE
Add custom select menu from cfgov-refresh as a CF component

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#128]
Assets:
- https://github.com/cfpb/cfgov-refresh/blob/bc74541c5f8d524929a0f50cdf5d8654dc7aaaeb/static/js/jquery.custom-select.js
- https://github.com/cfpb/cfgov-refresh/blob/bc74541c5f8d524929a0f50cdf5d8654dc7aaaeb/static/css/forms.less

Pinging https://github.com/cfpb/design-manual/issues/229#issuecomment-69374285

**Comment by contolini** [comment]
Necessary for 1.0?

**Comment by mebates** [comment]
Yo! Where's this at? Would love to close out the Design Manual issue and get this into our design templates. https://github.com/cfpb/design-manual/issues/229

**Comment by contolini** [comment]
@himedlooff Is this good-to-go? Does it just need to be packaged?

**Comment by himedlooff** [comment]
It's been in use in cfgov-refresh for a while so it seems safe to package it up. One thing that's missing are tests.

**Comment by contolini** [comment]
@himedlooff @Scotchester Is `custom-select` the best class for this? Why not something like `cf-select`?

**Comment by himedlooff** [comment]
I think `.custom-select` gives a clue that it's a more involved pattern, not just a `<select>` element, but I guess `.select-menu` or `.select` would work.

**Comment by contolini** [comment]
@himedlooff Cool, works for me.

**Comment by jimmynotjim** [comment]
This has been replaced and will become an atomic component during the workshop next week. Closing
