### ISSUE TITLE
Add bower and grunt-cli install to homepage?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#139]
It can be confusing to run the command from the homepage when you don't have bower or grunt-cli installed.

**Comment by contolini** [comment]
Looks like it now says:

> You will need <a href="http://nodejs.org/">Node.js</a>, <a href="http://yeoman.io/">Yeoman</a>, <a href="http://gruntjs.com/">Grunt</a>, and <a href="http://bower.io/">Bower</a> to run these commands.
