### ISSUE TITLE
grunt vendor post install task not running

### ISSUE THREAD

**Issue by ascott1** [cfpb/capital-framework#143]
After running `npm install`, `grunt vendor` should run as a npm postinstall script. This didn't seem to work and had to be run manually.

**Comment by Scotchester** [comment]
What project?

The generator [creates a different set of Grunt commands](https://github.com/cfpb/generator-cf/blob/master/app/templates/_Gruntfile.js#L309-L317) now, and it does run `bower install` and `grunt compile-cf` in [the npm `postinstall`](https://github.com/cfpb/generator-cf/blob/master/app/templates/_package.json#L37).

**Comment by ascott1** [comment]
Sorry, this static site specifically (not the components).

**Comment by Scotchester** [comment]
Ahah :+1:
