### ISSUE TITLE
Add note in Readme about denying incoming connections for node?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#146]
CFPB laptops get the following warning when installing the project:
![screen shot 2015-01-28 at 9 48 32 am](https://cloud.githubusercontent.com/assets/704760/5946658/7bcb0404-a705-11e4-9a74-151c8f9b1cc8.png)

Do we want to include a message in the Readme about this? Or since this is only probably going to be an issue for our particular CFPB laptop configuration, is it not worth mentioning in this public readme?

Here's some suggested copy to add to the troubleshooting section in the readme:

```markdown
**Deny/Allow connections.** If you are an employee of the CFPB, you may encounter the following message:

> Do you want the application "node" to accept incoming network connections

Hit `Deny` if you encounter this dialog.
```

**Comment by himedlooff** [comment]
I wouldn't mind seeing this in the readme, it's helpful.
