### ISSUE TITLE
Project Organization and Workflow

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#148]
Should this repo be updated to match the organization and workflow created by the generator? If I were to come to this repo trying to understand how a CF project works, I'd be really confused because my generated project wouldn't match up what I'm seeing here.

**Comment by ascott1** [comment]
Yes, yes it should. I think this has just fallen a bit behind.

**Comment by Scotchester** [comment]
For that to work, the generator would have to be update to be able to output a gh-pages branch with the content in the root. I'm currently testing out the grunt-gh-pages plugin to do this on another project. I will report back with how it goes.

**Comment by jimmynotjim** [comment]
I meant more the assets being in `/src` and `/dist` rather than `/assets` and `/build`. The content could stay in the root and templates be updated to link to a `/dist` directory.

**Comment by Scotchester** [comment]
Ah, good point!

**Comment by contolini** [comment]
Related question: When we tell people to download the compiled CSS, we send them to `cf.zip`. But that archive contains a demo page and a bunch of other stuff. The CSS is buried in `static/css/main.css`. Now that we have the generator, should `cf.zip` only contain the compiled CSS and JS?

**Comment by Scotchester** [comment]
I think including a simple demo page is still important.

1. Part of CF, in my mind, is offering best practice guidelines for how an
HTML file is structured.
2. People who want the compiled download for rapid prototyping shouldn't
have to bother with creating a re HTML file from scratch and attaching the
CF assets to it.

**Comment by contolini** [comment]
Cool, I'll restructure the archive. Assets in the root and a `demo` directory.
