### ISSUE TITLE
Should we stop using the autogenerated docs at this url?

### ISSUE THREAD

**Issue by ascott1** [cfpb/capital-framework#154]
Related to #153.

Right now the docs for individual components are autogenerated with Topdoc. This is awesome as part of the component repo, but they're a little confusing for users. Should we replace them with manually created pages that only contain:

- the demo of each pattern
- copyable markup for each pattern

:question: 

The problematic part is that we would have to manually updated the docs anytime a pattern is changed.

**Comment by himedlooff** [comment]
It would be cool if we could tag certain topdoc comments as "demos" or something, and then be able to have topdoc spit out a version that only shows demos.

**Comment by KimberlyMunoz** [comment]
Closing since we have discussion on this topic at https://github.com/cfpb/capital-framework/issues/191
