### ISSUE TITLE
One Point Oh

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#155]
Last year @himedlooff created a [1.0 milestone](https://github.com/cfpb/capital-framework/milestones/1.0) for Capital Framework but we didn't have time to pursue it. He was then abducted by aliens and is no longer with us. May he R.I.P.

Now that our team is larger, we not only have more resources but I've also received a lot of good feedback on ways CF can be improved. Let's fix its pain points and work toward a 1.0 release. Over the next few days I'll be going through this repo's issues and:

1. Closing old, irrelevant issues.
1. Assigning a point person for open issues, assigning them to the 1.0 milestone if applicable.
1. Creating new issues for Capital Framework tasks that should be completed before a 1.0 release.

I don't completely know what a 1.0 version of CF looks like, but @Scotchester and I brainstormed some goals earlier today. We welcome any and all ideas.

### Capital Framework 1.0 Goals

1. Remove all CFPB branding from Capital Framework codebase (#161).
  - Capital Framework should have sensible, non-CFPB defaults for color and font variables.
  - All CFPB branding should be applied to a Capital Framework project by overriding the default variables using Less or CSS.
2. Make Capital Framework easier to use (#162).
  - Refactor build process.
  - Add a big `Download Now` button to CF's homepage that points to a compiled CSS tarball.
  - Publish a few [example layouts](http://getbootstrap.com/getting-started/#examples) to help people get started.
3. All components have accessibility tests that are automatically run by Travis CI (#163).
  - Maybe using [SanityBox](https://github.com/anselmbradford/SanityBox)?
  - Sauce?
  - tenon.io?
4. Add more components to Capital Framework (#164).
  - What components do other UI frameworks have that CF doesn't?
  - Which of those would be most useful for CF?
  - Are there any current CF components that need refactoring/removing?

Stay tuned! Let's ship this thing! :rage1: :rage2: :rage3: :rage4: :feelsgood: :nail_care:

**Comment by himedlooff** [comment]
Thanks for starting this @contolini!
I have some thoughts from beyond the grave :ghost: 

To me a Capital Framework 1.0 should mean that all components composing it are >= 1.0. 1.0 for components should mean they work and are tested cross browser, are accessible and have a level of maturity i.e. is being used in a project.

**Comment by contolini** [comment]
@himedlooff Great points. We *need* automatic browser and accessibility testing for 1.0. I'll add them to the list.

**Comment by Scotchester** [comment]
Re: "Download now" button: See also #108 and #117

**Comment by mebates** [comment]
:tada: good work
May I also add an item at the end of the list:
5. Tell people about it (Open Tech blog, conference talks, twitter push, etc.)

**Comment by ascott1** [comment]
>  Tell people about it (Open Tech blog, conference talks, twitter push, etc.)

That's on our list @mebates! Once we hit 1.0, we're going to write a tutorial blog post on getting started with CF.

**Comment by contolini** [comment]
I wrote up formal steps over at #168.
