### ISSUE TITLE
Automated accessibility tools

### ISSUE THREAD

**Issue by ascott1** [cfpb/capital-framework#156]
Documenting the tools that came up today:

- https://github.com/addyosmani/a11y
- https://tenon.io
- https://github.com/yargalot/AccessSniff
- https://github.com/zrrrzzt/wcag-validator
- http://pa11y.org/

We also need a cool badge like these from Shields.io:

![https://img.shields.io/badge/508-compliant-brightgreen.svg](https://img.shields.io/badge/508-compliant-brightgreen.svg)

**Comment by contolini** [comment]
I think between a11y, pa11y and node-wcag we're good-to-go here.

**Comment by contolini** [comment]
All the components have Travis CI running pa11y tests!

**Comment by Scotchester** [comment]
![my-hero](https://cloud.githubusercontent.com/assets/1044670/7924365/90430ae6-0888-11e5-94ee-53e06db2b1b4.gif)
