### ISSUE TITLE
Components for 1.0 release

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#158]
Per goal 4 of #155: Which components will be part of 1.0?

### Necessary:
- cf-core
- cf-grid
- cf-icons
- cf-buttons
- cf-forms
- cf-pagination
- cf-expandables
- cf-layout
- cf-typography
- *capital-framework*
- *cf-grunt-config*
- *cf-component-demo*
- *generator-cf*

*Items in italics are repos that are necessary but are not traditional CF components.*

### Nice to haves:
- cf-tabs (See https://github.com/cfpb/cf-tabs/pull/3)
- cf-tables (See https://github.com/cfpb/cf-tables/issues/1)
- cf-alerts (See http://himedlooff.github.io/cf-alerts/docs/)
- cf-breadcrumbs (See https://github.com/himedlooff/cf-breadcrumbs)

### Removed:
- ~~cf-demo~~ (deprecated)
- ~~cf-colors~~ (deprecated)

How's this look? Anything I missed?

**Comment by anselmbradford** [comment]
Is there a canonical list of CF repos anywhere? I've been aggregating them in [GHE]/flapjack/Getting-started-with-Flapjack/issues/27, but just added cf-grunt-config because I hadn't heard of that one.

**Comment by Scotchester** [comment]
It's all the ones that start with `cf-` ;)

**Comment by contolini** [comment]
@anselmbradford Ah, that list is great!

**Comment by anselmbradford** [comment]
> It's all the ones that start with `cf-` ;)

Except for generator-cf and capital-framework ಠ_ಠ ... but yes the majority are easy to find :smile:

**Comment by himedlooff** [comment]
I started http://himedlooff.github.io/cf-alerts/docs/ and github.com/himedlooff/cf-breadcrumbs for dev dash. They are unofficial components however, no deign input.

**Comment by contolini** [comment]
@himedlooff Those alerts are gorgeous! I'll add them under nice-to-have for now.

**Comment by Scotchester** [comment]
I'm not sure those "meta" repos should be considered part of the "Capital Framework 1.0 Release". What exactly do we mean by that?

**Comment by Scotchester** [comment]
As an aside, Flapjack has been working on some alerts recently. /cc @duelj, @ajbush

**Comment by contolini** [comment]
@Scotchester 1.0 for the meta repos just means we have confirmed they work with the 1.0 versions of all the components.

**Comment by contolini** [comment]
Closing this because we agreed we're not adding any additional components to 1.0.
