### ISSUE TITLE
More expandable bg color modifiers - [Copied from FlapJack backlog]

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#159]
We need white and gray padded bg modifiers so we can do white single expandables or gray stacked expandable groups which makes this pattern way more versatile across different background types.

**Comment by anselmbradford** [comment]
Is this theoretical or do we have a location where this background variation is necessary? cc @nataliafitzgerald

**Comment by jimmynotjim** [comment]
😂 Like I can remember why we had this in the flapjack backlog over two years ago

**Comment by nataliafitzgerald** [comment]
@jimmynotjim @anselmbradford 
The only expandables I've seen on the website are the white background groups of expandables. That's not to say that we aren't using an individual white (or gray) or a group of gray, I just haven't seen it on our site. Is there a way for us to do a search and find everywhere a pattern is used on our site? 

I do see that we accounted for all these types in our DM: https://cfpb.github.io/design-manual/page-components/expandables.html

- Individual white
- Individual  gray
- Group white
- Group gray

**Comment by jimmynotjim** [comment]
The filterable list controls on the blog and newsroom are single gray expandables and well being results page uses a single white expandable https://www.consumerfinance.gov/consumer-tools/financial-well-being/results/

**Comment by jimmynotjim** [comment]
This was fixed in #787
