### ISSUE TITLE
Set up automated accessibility testing

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#16]
# Research

## Chrome DevTools Accessibility Extension

*Notes from OSCON 2013 courtesy of @Scotchester*

> [Install from the Chrome Web Store](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?utm_source=chrome-ntp-icon)

> Run accessibility tests from the Audits tab.

> Can access the API with Web Puppeteer. Tutorial on http://github.com/GoogleChrome (see slides for link).

## Case study: Case Commons using capybara-accessible

*Notes from OSCON 2013 courtesy of @Scotchester*

> Government child welfare organization, required to follow Section 508.

> Tech constraints: Rspec, Capybara

> Created a Capybara wrapper around the Chrome DevTools Accessibility Extension, baking the testing into their integration test suite. It's a drop-in replacement for a Selenium web driver in Capybara.

> It generates a build failure like any other integration testing error.

> To help locate problem spots, added a debugging snapshot right before the exceptions are thrown so that you can load it up in a browser and use the DevTools to see what's going on.

> http://github.com/CaseCommons/capybara-accessible

## Quail.js

> Accessibility testing in the browser and on the server.

> QUAIL is a jQuery plugin for checking content against accessibility guidelines. It provides a flexible way to test for certain problems (say, images missing an alt text) and a collection of over 200 tests to get you started. Defining your own tests is easy, and you can pick-and-choose tests to focus on the needs of your own app.

http://quailjs.org/

## Deque

> FireEyes is our free accessibility testing plug-in. With the click of a button, it can provide a detailed and comprehensive report of any accessibility errors on any of the pages within your site. You can then send that error report to the WorldSpace public server where you can download it as an Excel or .csv file.

> When you’ve got a big accessibility project, you need an automated testing tool that’s up to the task. WorldSpace combines the fast and thorough reporting capabilities of FireEyes and can use them across any quantity of pages. It also offers special features for managers, developers, and QA.

http://www.deque.com/products/

**Comment by KimberlyMunoz** [comment]
We now have pa11y and are in the process of getting node-wcag in our repos. I'll open a separate issue for that.
