### ISSUE TITLE
Base64 encoding the icon font

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#160]
@himedlooff @Scotchester Back in the day did you consider Base64 encoding the icon font? It would make cf-icons a whole lot easier to work with because you wouldn't have to ensure the font files are in the proper directory relative to your stylesheet.

I tried it and it seems to work well with a couple caveats:
- The encoded font is ~ 15% larger, is this performance hit acceptable?
- IE < 9 doesn't support Data URLS greater than 32KB so we still need an EOT fallback for IE8.

Here's the demo: http://contolini.github.io/cf-import-test/

The demo compiles all Less in the browser using less.js by pulling in a [single entry point](https://github.com/contolini/cf-import-test/blob/gh-pages/main.less#L7) for CF (see #151). Here's the [encoded font](https://github.com/cfpb/cf-icons/blob/dev/src/cf-icons.less#L83) that's being used. And here's a version of the demo with the Less [pre-compiled](http://contolini.github.io/cf-import-test/compiled-test/).

**Comment by Scotchester** [comment]
What's with the vertical alignment of the icons? (Look at one in a button.) Is that an artifact of the base64 encoding?

**Comment by ascott1** [comment]
It's possible that the performance could offset by the single http request. It'd be interesting to measure the difference. Do we have a similar demo without the encoded fonts to measure against?

**Comment by contolini** [comment]
@Scotchester Good eye on the alignment. I don't want to debug why that's happening so I'm going to move this idea to the backburner.

@ascott1 Great point. If you're interested in pursuing that experiment, let me know if I can help.

**Comment by jimmynotjim** [comment]
We've switched to inline SVG icons.
