### ISSUE TITLE
Remove all CFPB branding from Capital Framework codebase

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#161]
Goal 1 of #155.

- [x] Capital Framework should have sensible, non-CFPB defaults for color and font variables.
- [x] All CFPB branding should be applied to a Capital Framework project by overriding the default variables using Less or CSS. (See [`cf-theme-overrides`](https://github.com/cfpb/generator-cf/blob/master/app/templates/src/static/css/cf-theme-overrides.less).)

CFPB's color palette has already been removed from CF, only the fonts remain.

- Option 1: Simply delete this [@import statement](https://github.com/cfpb/cf-core/blob/6b834f8d6888177ddb97d323ff4f3802b6337c41/src/cf-base.less#L7). The [font mixins](https://github.com/cfpb/cf-core/blob/gh-pages/src/cf-base.less#L46-L87) will then default to Arial if `AvenirNextLTW01` isn't present.
- Option 2: Remove both the `@import` statement AND `AvenirNextLTW01` from the mixins. This solution is a little cleaner because non-CFPB people will never need `AvenirNextLTW01`.

The simpler option 1 is fine by me but if anyone prefers option 2 (or another solution), do speak up.

**Comment by Scotchester** [comment]
Agreed that the `@import` removal should definitely happen, so people aren't making four requests that will be blocked on every page load. We'll have to make sure our projects manually add this in to their `cf-overrides.less` file, though.

There's a tertiary goal of making it easier for people to use other typefaces, too. This is probably as simple as creating variables for serif and sans-serif font stacks (at different weights), and putting those variables in the mixins. This way, people can just change the font-stack variables and have it propagate everywhere.

**Comment by ascott1** [comment]
Great change. This puts us closer to making CF more extensible for non-CFPB branded projects. :boom: :rocket:

**Comment by contolini** [comment]
Nice work @KimberlyMunoz! Do you think we're ready to check off the first checkbox above?

@Scotchester How important is the tertiary goal you mention above? Do you view it as a 1.0 requirement?

**Comment by KimberlyMunoz** [comment]
I just have to tag new releases. I hope to get those in today!

**Comment by contolini** [comment]
:+1:

**Comment by Scotchester** [comment]
@contolini Nah, I wouldn't say it's a 1.0 requirement.

**Comment by KimberlyMunoz** [comment]
Quick PRs to update:

https://github.com/cfpb/cf-component-demo/pull/39
https://github.com/cfpb/generator-cf/pull/79
https://github.com/cfpb/cf-core/pull/38

**Comment by contolini** [comment]
https://github.com/cfpb/generator-cf/pull/79 is merged so it looks like we're done here. :smiley:
