### ISSUE TITLE
All components have browser and accessibility tests that can be easily run from the command line

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#163]
Goal 3 of #155.

- [x] Run all components' demos' HTML through [pa11y](https://github.com/nature/pa11y) via Travis CI. Add badge to each README. @contolini (being reviewed by @anselmbradford)
- [x] Configure Travis to run cf-expandables' JS unit tests. @contolini
- [x] CSS regression testing is on hold for now.

**Comment by contolini** [comment]
@anselmbradford has graciously volunteered to review all my pa11y pull requests.

**Comment by contolini** [comment]
Donezo!

**Comment by anselmbradford** [comment]
noice!
