### ISSUE TITLE
Audit component repos

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#164]
Goal 4 of #155.

- [x] We agreed we're not going to worry about adding new components.
- [ ] Explain certain sections better (e.g. colors and sizings at the top of http://cfpb.github.io/cf-buttons/docs/) or just remove them. @Scotchester 
- [x] Remove compiled CSS from right side of docs pages. @Scotchester (PR https://github.com/cfpb/cf-component-demo/pull/40)
- [x] ~~Delete deprecated components from GitHub.~~ Decided to leave deprecated repos. @contolini

**Comment by contolini** [comment]
@Scotchester Think you'll have time to get to no. 2 today or tomorrow? Otherwise I'll bump it to v1.1.

**Comment by Scotchester** [comment]
I will not, sadly. 1.1 it is.

**Comment by contolini** [comment]
No biggie.
