### ISSUE TITLE
Tooltip Component

### ISSUE THREAD

**Issue by ascott1** [cfpb/capital-framework#167]
Looking at [front-end #46](https://github.com/cfpb/front-end/issues/46), we're using a few different tooltip plugins (Bootstrap and tooltipsy). Should we introduce a CF tooltip component? If yes, I'll offer to write it.

A couple of questions:
1. Have we settled on design standards for tooltips? @Scotchester @mebates @stephanieosan @benguhin
2. How do we want to write JS CF components going forward? My gut reaction is to write them as [UMD](https://github.com/umdjs/umd) style jQuery plugins.

**Comment by mebates** [comment]
The design standard hasn't been settled. @huetingj has been working on it recently: https://github.com/cfpb/design-manual/issues/139

**Comment by ascott1** [comment]
Sounds like good timing then! Once this is standardized, let's make it a CF component so we're not constantly restyling other libraries.

**Comment by stephanieosan** [comment]
Ooooooh, tooltips of our own!

**Comment by contolini** [comment]
@ascott1 You could probably start hacking out the functionality even if the design isn't finalized yet. Also: great idea!

**Comment by stephanieosan** [comment]
I will re-open the design tooltips conversation to try to get a solution for you, @ascott1 :)

**Comment by ascott1** [comment]
[This comment](https://github.com/cfpb/design-manual/issues/139#issuecomment-107711520) by @stephanieosan gives a really thorough description of the desired implementation.

**Comment by ascott1** [comment]
And [we have a repo](https://github.com/cfpb/cf-tooltips). :tada:

**Comment by jimmynotjim** [comment]
The Design team has killed tooltips. RIP, we hardly knew ye. @ascott1 is our repo deprecation process documented somewhere or can I just go ahead and take a stab at it?

**Comment by anselmbradford** [comment]
Can this be closed? @jimmynotjim @ascott1

**Comment by ascott1** [comment]
Good catch - closing!

**Comment by mebates** [comment]
👋 old friends! love it when you pop up in my email box. RIP tooltips, but good.

**Comment by ascott1** [comment]
Hi @mebates!
