### ISSUE TITLE
Document all components on a single page

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#170]
I don't think this idea has been covered before, but @niqjohnson suggested that having a page [like Bootstrap's showing every component](http://getbootstrap.com/components/) would be helpful. I tend to agree.

The one thing that gives me pause is the maintenance headache of having to update two repos (the actual component and then the docs) any time you make a change that requires updating the docs.

I have a couple ideas to get around that:
1. Come up with some way to dynamically generate the page client-side by fetching the latest code/docs from each component's repo
2. Figure out how to use GitHub's webhooks to trigger a doc rebuild whenever a component is updated

Thoughts, @cfpb/front-end-team-admin @cfpb/front-end-team-write ?

**Comment by niqjohnson** [comment]
To elaborate a little more: I've used Bootstrap to prototype/design in the browser for a while, and there are a few things about their docs that make that job a lot easier:

- The docs are (usually) authoritative and up to date, so I know I can go to one place to find out how to use any component I need (and be pretty confident that, if I can't find the component there, it doesn't exist)
- The docs show how different components can be combined, so I know how to use, say, a dropdown inside a navbar
- The docs have lots of easily copy-and-pasteable snippets, so I can drop a complex component in a prototype really quickly

I'd love it if Captial Framework had something similar—basically, a single page (or very small collection of pages) where I can grab any component I need, drop it into an HTML prototype, and learn how to modify or extend it.

**Comment by KimberlyMunoz** [comment]
I agree something like that would be useful. Especially for something like the more visual components like cf-icons. 

We could revamp the demo pages and link to those, however that really doesn't show how the components can be combined. That would seem to require some human curation.

**Comment by jimmynotjim** [comment]
We didn't end up using them in a single page, but we did create a sandbox that removes all the documentation to make it easier to see just the components. @niqjohnson take a look at https://cfpb.github.io/capital-framework-sandbox/components/ and let me know if that's about what you were looking for. It's built upon this repo's gh-pages but with a few tweaks.

**Comment by niqjohnson** [comment]
The sandbox plus the new documentation pages have been working great for me lately. 👍

**Comment by jimmynotjim** [comment]
Awesome. Let's consider this resolved and if a future problem arrises we can address it in a new issue.
