### ISSUE TITLE
Icons on the homepage not working

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#178]
The icon font isn't loading and thus the icons are not showing up:

![image](https://cloud.githubusercontent.com/assets/1093373/8011414/8578336a-0b86-11e5-93b2-59a2b82b5507.png)

**Comment by contolini** [comment]
Whoopsie, it works locally but that's because `fonts/` is being ignored in `.gitignore`. I'll fix that. Related to https://github.com/cfpb/capital-framework/issues/176.

**Comment by ascott1** [comment]
This still isn't working for me. :frowning:
