### ISSUE TITLE
[VZ] SemVer conventions

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#179]
This is to ensure we're all on the same page w/r/t Capital Framework hygiene.

> What happens when a CF component increments its patch version? (e.g. cf-buttons going from 1.0.0 to 1.0.1)?

The master component (this repo) doesn't increment anything because the caret notation in [`bower.json`](https://github.com/cfpb/capital-framework/blob/gh-pages/bower.json) ensures the latest version of the component (up to and excluding new major versions) will be installed.

> What happens when a CF component increments its minor version? (e.g. cf-buttons going from 1.0.1 to 1.1.0)?

The master component doesn't increment anything because the caret notation in [`bower.json`](https://github.com/cfpb/capital-framework/blob/gh-pages/bower.json) ensures the latest version of the component (up to and excluding new major versions) will be installed.

> What happens when a CF component increments its major version? (e.g. cf-buttons going from 1.1.0 to 2.0.0)?

The master component increments its major version (e.g. 1.1.5 -> 2.0.0) because there are breaking changes downstream.

> What happens when CF gets a new component? (e.g. https://github.com/cfpb/capital-framework/issues/167)

The master component increments its minor version (e.g. 1.1.5 -> 1.2.0) because new, backwards-compatible changes have been introduced. The new component should be added as a dep to [`bower.json`](https://github.com/cfpb/capital-framework/blob/gh-pages/bower.json) with caret notation (e.g. `cf-tooltip: ^0.1.0`). The new component itself should remain 0.x.x until it exits beta. Once it exits beta, see below.

**Note:** It is acceptable for components in beta to introduce breaking changes when incrementing their minor version (e.g. 0.2.0 to 0.3.0). Beta components should be considered experimental until they reach 1.x.x, at which point their API is frozen.

> What happens when a CF component exits beta (going from 0.x.x to 1.x.x)? (e.g. cf-tooltip going from 0.6.0 to 1.0.0)?

The master component's [`bower.json`](https://github.com/cfpb/capital-framework/blob/gh-pages/bower.json) is updated (e.g. `cf-tooltip: ^1.0.0`) and the master component increments its minor version because the update to `bower.json` is a backwards-compatible change. 

> What happens when CF removes a component?

The master component should increment its minor version (e.g. 1.1.5 -> 1.2.0) because new, backwards-compatible changes have been introduced. The new component should be removed from `bower.json`.

> When should the patch version of the master repo be incremented?

When you do something inconsequential to this repo, like change instructions in the readme, move something around in package.json, etc.

Feedback greatly appreciated @cfpb/front-end-team-admin

**Comment by KimberlyMunoz** [comment]
I think this sounds great, but I'd just suggest making this into a table and adding it to CONTRIBUTING.md for reference.

**Comment by contolini** [comment]
Relevant: https://github.com/semantic-release/semantic-release

**Comment by contolini** [comment]
I'm now realizing this will be an incredibly important issue once we have everything in one repo and are relying on auto-publishing scripts. Gonna codify it for CFv2.

**Comment by contolini** [comment]
After writing the code to implement this, I think the symbiosis introduced by Voltrazord changes this versioning strategy. Now that the components are stored inside of the master `capital-framework` repo, a non-breaking change to `cf-whatever` is also a non-breaking change to `capital-framework` since its the same codebase.

I think it makes our versioning less complicated: when a component increments its major/minor/patch version, the master component increments the same version.

**Comment by Scotchester** [comment]
@contolini As a baseline rule, I like that. My only concern is that I don't think I'd want `capital-framework` to automatically get a new version/release immediately when a component is updated. There may be times when we want to batch updates to multiple components together in one release of the complete framework.

**Comment by contolini** [comment]
@Scotchester Can you provide an example of when we'd want to do that? If there's new code entering master, I'd feel obligated to increment capital-framework's version number.

**Comment by jimmynotjim** [comment]
The recent changes to headings would be a good example. It required changes to core plus three different components.

**Comment by contolini** [comment]
In that situation I envision a WIP pull request being opened and it not
being merged into master until all three components have been updated.
They'd all enter master at once and CF gets bumped appropriately.

On Monday, December 7, 2015, Jimmy Wilson <notifications@github.com> wrote:

> The recent changes to headings would be a good example. It required
> changes to core plus three different components.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfpb/capital-framework/issues/179#issuecomment-162668672>
> .
>


-- 
Chris

**Comment by jimmynotjim** [comment]
Oh yeah, guess that makes sense. I'm convinced :+1:

**Comment by contolini** [comment]
It'd also be fine if the components were updated one-by-one but every time
an updated component entered master I'd expect a CF bump.

Chris

**Comment by Scotchester** [comment]
I believe this is closed now that Voltrazord is done. Feel free to re-open if I missed something.
