### ISSUE TITLE
Create a component generator

### ISSUE THREAD

**Issue by ascott1** [cfpb/capital-framework#182]
Creating a new CF component involves a lot of copy and pasting from an existing CF component. Should we make a generator to simplify this process? It may make spinning up the new components for the design manual quicker.

cc: @cfpb/front-end-team-write @cfpb/front-end-team-admin

**Comment by wpears** [comment]
Prepare for an unfortunate naming conflict with [generator-cf](https://github.com/cfpb/generator-cf)! Otherwise, sounds good if you expect there to be an upswing in the amount of new components created.

**Comment by ascott1** [comment]
I'm thinking `generator-cf-component`?

**Comment by wpears** [comment]
:rocket: You are requested and required to make it so :rocket:

Go forth and generate

**Comment by Scotchester** [comment]
Yessssss :+1:

**Comment by contolini** [comment]
Do it in Go.

Chris

**Comment by jimmynotjim** [comment]
I'd appreciate this because I have two components to build still.

**Comment by ascott1** [comment]
This initial version of this exists: https://github.com/cfpb/generator-cf-component! 

Subsequent issues can be in that repo.
