### ISSUE TITLE
No documentation for cf-typography

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#190]
CF-typography's readme directs people to the Capital Framework documentation site for documentation. It's not included there.

https://cfpb.github.io/capital-framework/components/

**Comment by Scotchester** [comment]
It's a little nuanced, but that's supposed to be talking about how to include cf-typography in your project. The Docs and Demo are linked at the top of the README, and at the top of the page.

**Comment by KimberlyMunoz** [comment]
So cf-typography should be missing from this list of components?

**Comment by Scotchester** [comment]
Oh, I see what you're saying. No, it should not be missing from that page.

**Comment by KimberlyMunoz** [comment]
Typography has a page now! 

https://cfpb.github.io/capital-framework/components/cf-typography/
