### ISSUE TITLE
Should we stop using auto-generated docs?

### ISSUE THREAD

**Issue by ascott1** [cfpb/capital-framework#191]
The idea behind auto-generated documentation is a very good one, but in practice it has caused the documentation site to feel splintered and difficult to navigate.

I propose that we move from auto-generated docs to manually maintaining pages as party of the github.io site.

Some advantages:

- It gives us greater control over the documentation as a whole
- It means that we're not including documentation source in the individual repos (which is then downloaded as part of those packages)
- It provides greater visual consistency between the component documentation and the github.io site
- We an add some other documentation nice to haves (to be detailed in future issues)
- Potentially ends the circular dependency weirdness of cf-core and cf-component demo

The only disadvantage that I can come up with, is that we will have to update the documentation site when we update a package. If we fail to do this, the docs could become outdated.

Thoughts? CC @cfpb/front-end-team-admin

**Comment by KimberlyMunoz** [comment]
I want to follow this issue because the auto-generated docs were one of the biggest things I struggled with when I first started contributing to CF. The way our docs are generated (and the usefulness of our docs in general) is a huge barrier to entry and we don't do a good job of documenting our documentation process. 

Here are some of the issues I have with the auto-generated docs right now:
- Small issues can break topdoc without any useful errors for debugging
- It's very difficult to find where something is if it's split among multiple components. (I struggle the most with information that's in typography or core)
- If a certain pattern uses multiple components, it can be difficult to add that to the documentation.
- There are so many modules that the "guess the module" game is taking more time and even more of a barrier for newcomers.

**Comment by KimberlyMunoz** [comment]
One more thing, anytime any piece of CF gets updated the other modules will have a diff with documents and demos, which means we're constantly checking in the newest changes there and seeing this. Even if we're checking in a change that has nothing to do with those recently merged PRs.

![image](https://cloud.githubusercontent.com/assets/1860176/10621686/3bd15e90-7750-11e5-8959-77d4edaefdd7.png)

**Comment by KimberlyMunoz** [comment]
Another thing. Our demos are filled with errors from our accessibility testing and fixing it one place takes forever, much less fixing it in all the repos. Switching over to the 18F colors will help, but it'd be much less stressful to maintain in one place.

**Comment by cfarm** [comment]
Yes kill it

We should integrate CF documentation in the Design Manual where it belongs, like the [US Web Design Standards](https://playbook.cio.gov/designstandards/).

**Comment by cfarm** [comment]
Goals for Design Manual Docs: 

* Docs are still updated and maintained in one place (CF)
* Markup code snippest are imported to Design Manual for easy reference
* Design Manual links to related components docs in CF for more detailed implementation notes

**Comment by ascott1** [comment]
I think @cfarm describes a good hybrid approach. Full documentation can live here while copy and paste-able markup can also exist in the design manual for easy reference.

**Comment by Scotchester** [comment]
I can dig it, @cfarm. I think that's actually something we wanted to do back in the day, just couldn't get around to it.

**Comment by Scotchester** [comment]
"that" = somehow semi-automagically getting markup snippets from CF into the DM.

**Comment by contolini** [comment]
Yinz have any thoughts on implementation details? How do you see docs living here and being consumed elsewhere (i.e. in the design manual)?

Proposal: Have a `docs.md`, `snippets.md` and `preview.html` in each component directory. They can be pulled into the design manual via a Grunt task. Using cf-buttons as an example:
- `preview.html` contains markup of all the buttons in their various states. It's rendered at the top of the manual's buttons page.
- `snippets.md` contains code samples for copying/pasting. It is parsed and rendered into an expandable below the rendered buttons.
- `docs.md` contains optional component usage notes.

The above works for the [USWDS layout](https://playbook.cio.gov/designstandards/buttons/) but doesn't actually work with our layout. Our [docs and previews](https://cfpb.github.io/design-manual/ui-toolkit/buttons.html) are side-by-side. Sooooo this isn't a great proposal but I'd love to find a hybrid solution to avoid having to manually update the design manual every time we change a component. Things'll get stale real quick.

**Comment by ascott1** [comment]
> Yinz

Well played.

I agree that manually updating the design manual is less than ideal, though @contolini's proposal would still require some manual intervention to get the design manual to build with updates (unless I'm mis-understanding). 

**Q:** How often does just the markup of a CF component in the design manual change? Is something like above worth the initial overhead? I want to avoid any solution that overcomplicates things in an attempt at simplicity.

**Comment by contolini** [comment]
Making manual updates in *two* places is what I'd like to avoid. If we're only manually updating one place -- the design manual -- then I don't think we need any automagic processes like the one I described above.

**Comment by anselmbradford** [comment]
Sorry for the lack of implementation details, but it seems like it would be helpful to pipe `preview.html` as a stub into an automated test that checks for adherence to the specifics Design mocked up.

**Comment by contolini** [comment]
> Sorry for the lack of implementation details, but it seems like it would be helpful to pipe preview.html as a stub into an automated test that checks for adherence to the specifics Design mocked up.

:heart_eyes:

**Comment by Scotchester** [comment]
Superseded by the two new doc improvement paths #242 and #243).
