### ISSUE TITLE
Create a sample page/layout as part of the documentation

### ISSUE THREAD

**Issue by ascott1** [cfpb/capital-framework#192]
Something along the lines of http://www.basscss.com/docs/guides/layout/

**Comment by contolini** [comment]
:100: deargodyesplz

**Comment by KimberlyMunoz** [comment]
Yes! Somewhat related to https://github.com/cfpb/capital-framework/issues/191

**Comment by jimmynotjim** [comment]
This is done yeah?

**Comment by Scotchester** [comment]
@ascott1 That basscss page is gone. Can you please describe what kind of sample thing it was that you wanted?

**Comment by anselmbradford** [comment]
There used to be a page like this somewhere… maybe in a wiki? It documented the base template layouts found in cfgov-refresh, but may be covered now more or less in the cf-layout documentation. Can we close this?

**Comment by anselmbradford** [comment]
Closing as referenced link is dead and we have similar docs in cf-layout. Documenting the wagtail templates in cfgov-refresh seems to be what this would ultimately be for, which should probably happen there and fits in with Andy's idea of a pattern library in cfgov-refresh.
