### ISSUE TITLE
Ditch purple and provide a nicer default color scheme

### ISSUE THREAD

**Issue by ascott1** [cfpb/capital-framework#193]
It makes sense to not use CFPB colors by default, but the current default color scheme means that anyone outside of CFPB who would like to use CF would need to use a color overrides file to make anything look reasonable. What about defaulting to a nice non-CFPB color scheme such as http://clrs.cc/

**Comment by wpears** [comment]
Can you expand on why it makes sense not to use CFPB colors by default? I understand we don't want CF coupled too tightly too cfpb styles, etc., but imo the visual carry over between CFPB styles as implemented on public sites and in the docs would probably help more than it would hurt

**Comment by ascott1** [comment]
I _think_ that early on there was a request not to couple it too much to our brand. @Scotchester or @himedlooff may be able to expand on that better.

**Comment by KimberlyMunoz** [comment]
YES! 

How would folks feel about cribbing the colors from 18F's Web Standards for the non-CFPB defaults? https://playbook.cio.gov/designstandards/visual-style/#colors

**Comment by contolini** [comment]
@KimberlyMunoz :+1: Makes sense to me.

**Comment by ascott1** [comment]
_Great_ idea @KimberlyMunoz! :us:

**Comment by Scotchester** [comment]
:a: :heavy_plus_sign: idea, @KimberlyMunoz!

**Comment by KimberlyMunoz** [comment]
Added a PR to cf-core to start porting over the 18F colors. https://github.com/cfpb/cf-core/pull/52

**Comment by mistergone** [comment]
:+1: to @KimberlyMunoz, love this idea.

**Comment by KimberlyMunoz** [comment]
Added to cf-typography. https://github.com/cfpb/cf-typography/pull/43

**Comment by KimberlyMunoz** [comment]
Moved from https://github.com/cfpb/cf-buttons/issues/39 and applies generally to all cf-components.

While updating this project @anselmbradford  realized the `CONTRIBUTING.md` and docs he looked at on http://cfpb.github.io/capital-framework/contributing/ are too generic to guide a contributor in what needs to be done when fixing an issue and contributing to the project. Specifically what installation and grunt commands need to be run, what needs to happen with the changelog, etc.

- [x] cf-core
- [ ] cf-grid
- [ ] cf-icons
- [ ] cf-buttons
- [ ] cf-forms
- [ ] cf-pagination
- [ ] cf-expandables
- [ ] cf-layout
- [x] cf-typography

**Comment by Scotchester** [comment]
End of Sprint 1 update: @KimberlyMunoz Started testing stuff out, but brokenness in generator-cf was making things difficult. Will pick this up in Sprint 2 when generator-cf is fixed.
