### ISSUE TITLE
Should we be more explicit around pegging dependencies?

### ISSUE THREAD

**Issue by ascott1** [cfpb/capital-framework#195]
This would force us to manually update components that rely on other components, but could avoid breaking stuff.

I'm also not super clear on the difference between using `~` and `^`.

**Comment by jimmynotjim** [comment]
I'm against pegging for reasons I pointed out in [Growing Pains](https://github.com/cfpb/capital-framework/issues/196#issuecomment-150240278)

**Comment by jimmynotjim** [comment]
done with shrinkwrapping.
