### ISSUE TITLE
[VZ] Sprint 1

### ISSUE THREAD

**Issue by cfarm** [cfpb/capital-framework#199]
This is what we decided to work on for our first CF 'sprint' at the last FEWD meeting

1. Make the components easier to find and contribute to, by combining into one repo. @contolini 

2. Make the documentation easier to find + use as a CFPB FEWD, by exploring 2 options: the Github repo (@ascott1); Design Manual (@cfarm)

**Comment by KimberlyMunoz** [comment]
One other thing we discussed (a subtask of 1) is to make issues easier to organize by combining them into one repo.

**Comment by jimmynotjim** [comment]
We should include the v2 release of cf-layout and the breaking changes to colors proposed by the Design team
