### ISSUE TITLE
Framework logo

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#20]
A logo would make Capital classier. We can stick it on the [demo page](http://cfpb.github.io/capital-framework/) and we'll need one if we end up moving the framework to a dedicated GH org.

Any ideas? Perhaps the standard four column government-looking building? Or a silhouette of the Capitol building? Or something money-themed like a seal on a U.S. dollar bill?

![300px-government_icon_symbo_01](https://f.cloud.github.com/assets/1060248/2326951/57ce0e40-a3e9-11e3-9f1f-72a9e02ff6b2.jpg)
![icon-government](https://f.cloud.github.com/assets/1060248/2326952/59f81b2a-a3e9-11e3-9e73-9e28451f3ebb.png)
![one_dollar_bill_reverse-united_states_](https://f.cloud.github.com/assets/1060248/2326953/5c08e8d6-a3e9-11e3-8039-5e52d5c2d60d.jpg)

**Comment by ascott1** [comment]
This graces our stickers and has sort of become our unofficial logo: ![modular](https://cloud.githubusercontent.com/assets/212533/7356286/1021de40-ecf5-11e4-8830-ec6688467fc3.png)

It's very different than what we planned, but I like it! Should we roll with this and close the issue?

**Comment by Scotchester** [comment]
Yeah. I'd still like to have something eventually that ties in a capitol building, but what we have is great for now. One small note: The one you pasted (the one from the docs site), is slightly cut off at the bottom. Should see the "bottom padding" of those three bottom-most blocks, as well as the darker edge. The stickers have this, so it's not a problem with the source file, but we should update that on the homepage sometime.

**Comment by ascott1** [comment]
That's odd and yes we should

**Comment by contolini** [comment]
I dig @ell0ell0's lego blocks a lot. The only issue is that it doesn't scale well. We'll need a version with fewer dimples if we plan on shrinking it to place in a header.

**Comment by himedlooff** [comment]
I think we have the `.ai` file if we need it

**Comment by Scotchester** [comment]
:'(
