### ISSUE TITLE
[cf-buttons] Add Full Width Buttons

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#201]
Moved from https://github.com/cfpb/cf-buttons/issues/49

The `__full` modifier needs to be ported [from cfgov-refresh](https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/preprocessed/css/cf-enhancements.less#L1191-L1214), but should be renamed to `__full-on-xs` to match the updated size naming schemes.

**Comment by jimmynotjim** [comment]
In-progress, see #483
