### ISSUE TITLE
[VZ] Adding Repository Fields to other cf-components

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#202]
This is an issue on multiple repositories. It was resolved on cf-icons in https://github.com/cfpb/cf-icons/pull/52 but needs to be added to other repos.

Without the repo fields this error happens:
`npm WARN package.json @ No repository field.`

Reported in:
https://github.com/cfpb/cf-buttons/issues/43
https://github.com/cfpb/cf-core/issues/37
https://github.com/cfpb/cf-forms/issues/31
https://github.com/cfpb/cf-expandables/issues/50
https://github.com/cfpb/cf-layout/issues/12

- [x] cf-core
- [x] cf-grid
- [x] cf-icons
- [x] cf-buttons
- [x] cf-forms
- [x] cf-pagination
- [x] cf-expandables
- [x] cf-layout
- [x] cf-typography
- [x] capital-framework
- [x] cf-grunt-config
- [x] cf-component-demo
- [x] generator-cf

**Comment by contolini** [comment]
Having everything in one repo will make fixes like this sooooo much easier.

**Comment by KimberlyMunoz** [comment]
Worrrrd

**Comment by contolini** [comment]
:+1: Voltrazord is alive. Voltrazord has destroyed this issue.
