### ISSUE TITLE
[VZ] Update CONTRIBUTING.md to give workflow for contributing

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#203]
Moved from https://github.com/cfpb/cf-buttons/issues/39 and applies generally to all cf-components.

While updating this project @anselmbradford  realized the `CONTRIBUTING.md` and docs he looked at on http://cfpb.github.io/capital-framework/contributing/ are too generic to guide a contributor in what needs to be done when fixing an issue and contributing to the project. Specifically what installation and grunt commands need to be run, what needs to happen with the changelog, etc.
- [ ] cf-core
- [ ] cf-grid
- [ ] cf-icons
- [ ] cf-buttons
- [ ] cf-forms
- [ ] cf-pagination
- [ ] cf-expandables
- [ ] cf-layout
- [ ] cf-typography
- [ ] capital-framework
- [ ] cf-grunt-config
- [ ] cf-component-demo
- [ ] generator-cf

**Comment by jimmynotjim** [comment]
There is a single contributing file in the main repo and it's pretty robust. @anselmbradford having run it again recently, is there anything you think we need to add/change that can be addressed in this issue?

**Comment by jimmynotjim** [comment]
@anselmbradford bumpity bump. I'm pretty sure we can close this one.

**Comment by anselmbradford** [comment]
Sounds good 👍 I'll be running through them again sometime after the 11th and will re-open if necessary.
