### ISSUE TITLE
[cf-core] Should the base font be changed to avenir?

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#206]
There is discussion at https://github.com/cfpb/cf-core/issues/22

**Comment by jimmynotjim** [comment]
This has been done in cfgov-refresh and should make it's way into the cfpb theme for Capital Framework that @Scotchester is working on.

**Comment by jimmynotjim** [comment]
@Scotchester is now including it in the atomic update to [cf-core](https://github.com/cfpb/capital-framework/issues/352), closing in favor of that issue.
