### ISSUE TITLE
[cf-core] Max-Widths on paragraph

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#207]
There was discussion on setting a rule on max-width with ems for long headings and/or paragraphs. The use case is that it would prevent paragraphs from getting past a readable length.

https://github.com/cfpb/cf-core/issues/25

**Comment by jimmynotjim** [comment]
This was [addressed by the Platform team](https://github.com/cfpb/cfgov-refresh/pull/2475/files#diff-b6e78e12f3348c69634c6b95cd89390cR210) and should be migrated to this project.
