### ISSUE TITLE
[VZ] Manifest strategy

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#210]
In progress proposal. Feedback welcome.

Every CF component will have it's own dir in the capital-framework repo. In each dir, a `package.json` file will serve as its manifest. It will:

- Store basic metadata (name, description, version number, keywords)
- List the component's required dependencies (both external deps like `normalize.css` and internal ones like `cf-core`)
- *Not* list dev dependencies. With everything moving into one repo, all building and testing deps will be listed in the higher-level capital-framework `package.json`.
- Have a `main` property pointing to the component's primary JS file.
- Have a `less` property pointing to the component's primary Less file.
- Have a `style` property pointing to the component's primary CSS file. The CSS will be generated in a pre-publish hook and likely not stored in git.

At ~~publish~~ *build* time, component manifests will be merged with a "default" manifest that holds metadata that is the same for all components (fields like `author` and `repository`). A new merged package.json file is created that will be published with the component's code to npm.

For example:
- [cf-button's manifest](https://gist.github.com/contolini/04e79e52f45afe893bfb#file-cf-buttons-package-json)
- [Default manifest](https://gist.github.com/contolini/04e79e52f45afe893bfb#file-default-package-json)
- Resulting [merged manifest](https://gist.github.com/contolini/04e79e52f45afe893bfb#file-resulting-package-json)

npm is schemaless so it's okay to add whatever properties we'd like to`package.json` The main/less/style properties are common among [UI](https://github.com/twbs/bootstrap/blob/50bea4625a09d14cec93e4dbdd9d336005ac7d85/package.json#L19-L21) [frameworks](https://github.com/basscss/basscss/blob/04fef0b2bc80d08d0f3d94b970ac3b6ed5f0d420/package.json#L5).

No more `bower.json`. If we decided to publish individual packages to Bower, we'll generate a `bower.json` programmatically using the fields in `package.json`.

**Comment by mistergone** [comment]
> npm is schemaless so it's okay to add whatever properties we'd like topackage.json The main/less/style properties are common among UI frameworks.

:+1: 

> No more bower.json. If we decided to publish individual packages to Bower, we'll generate a bower.json programmatically using the fields in package.json.

:+1:

If we are going to do one repo, I like all this. :heavy_plus_sign::100:

**Comment by contolini** [comment]
Implemented via a gulp task: https://github.com/cfpb/capital-framework/blob/canary/scripts/gulp/copy.js#L38-L55
