### ISSUE TITLE
[cf-core] IE 11: Link underline only appears on first line

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#211]
From https://github.com/cfpb/cf-core/issues/43

While testing on IE11, we notice that if a link extended to the 2nd line, the underline style can only be seen on the first line.

<img width="772" alt="screen shot 2015-08-25 at 6 40 12 pm" src="https://cloud.githubusercontent.com/assets/2673022/9481982/28ec49d0-4b5d-11e5-831c-53a1c23fdb8e.png">

<img width="1070" alt="screen shot 2015-08-27 at 10 33 36 am" src="https://cloud.githubusercontent.com/assets/778171/9528006/494ccb78-4ca7-11e5-933b-48b2c262db85.png">

**Comment by Scotchester** [comment]
Can't find evidence that this is still a problem.
