### ISSUE TITLE
[cf-core] Set up self-hosted webfonts 

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#213]
Original issue: https://github.com/cfpb/cf-core/issues/33 

The code provided for using our webfont provider's CDN is not cutting it. We need to set up our fonts to be self-hosted. It's essentially a three-step process:
- [ ] Upload font files to a location on one of our servers
- [ ] Get access controls in place (to ensure fonts can only be accessed from approved hostnames)
- [ ] Update the `@font-face` code in this repo to refer to the new locations.

And then projects will need to update their version of cf-core to use the new self-hosted fonts.

/cc @poorgeek

**Comment by jimmynotjim** [comment]
Related, I saw this yesterday - https://www.zachleat.com/web/comprehensive-webfonts/

**Comment by anselmbradford** [comment]
Added in https://github.com/cfpb/capital-framework/pull/672
