### ISSUE TITLE
Align CF Readmes with OS project template

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#214]
Original issue: https://github.com/cfpb/cf-core/issues/32

Move CF projects toward using a Readme more in-line with https://github.com/cfpb/open-source-project-template. Of particular note:
- Include the `LICENSE` (or exclude the link from the Readme). See https://github.com/cfpb/cf-typography/issues/31.
- Include installation instructions for generating the docs. E.g. Run `npm install`, `grunt vendor`, and `grunt` and open the HTML page in `/docs/` in a web browser (also may be worth noting a server doesn't need to be running). 
- Consider captioning the screenshot. The screenshot may be self-explanatory in some cases, but other times it may not be clear what's shown. For example, the cf-typography repo has a paragraph of text that turns into an image of lorem ipsum without any explanation of what the reader is looking at:

----------------------------
![screen shot 2015-03-19 at 2 41 10 pm](https://cloud.githubusercontent.com/assets/704760/6738099/25e71416-ce46-11e4-9c53-2292d148a434.png)
----------------------------

Without prior familiarity with the output of the project docs, it's not clear what this image is showing.

- [ ] cf-core
- [ ] cf-grid
- [ ] cf-icons
- [ ] cf-buttons
- [ ] cf-forms
- [ ] cf-pagination
- [ ] cf-expandables
- [ ] cf-layout
- [ ] cf-typography
- [ ] capital-framework
- [ ] cf-grunt-config
- [ ] cf-component-demo
- [ ] generator-cf

**Comment by mistergone** [comment]
I'll take these ones on as soon as I can:
- [ ] cf-tables
- [ ] cf-tooltips

**Comment by jimmynotjim** [comment]
Now that we're using the usage.md files for individual component readmes, is this still an issue?

**Comment by KimberlyMunoz** [comment]
Close it. We have this covered in so many documentation issues.
