### ISSUE TITLE
[cf-icons] Make a more user-friendly demo page

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#219]
Original issue: https://github.com/cfpb/cf-icons/issues/13

Currently, neither the docs nor demo pages do a great job giving a simple high-level overview of what cf-icons has to offer. Compare with the [Font Awesome icon list](http://fontawesome.io/icons/). I think we should develop a similar page for cf-icons.

Options for where this page could live:
- In this repo, along side the existing docs and demo
  - Probably means creating a new Topdoc template
- As part of the output of [cf-demo](https://github.com/cfpb/cf-demo)
  - As that page gets increasingly long/complex, does it need internal navigation?
- As a page on the [main docs site](http://cfpb.github.io/)
  - Do other components get their own demo page?

**Comment by anselmbradford** [comment]
We have an icon list in the docs at https://cfpb.github.io/capital-framework/components/cf-icons/#the-icons that should satisfy this issue.
