### ISSUE TITLE
[cf-icons] SVG over icon font option?

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#220]
https://github.com/cfpb/cf-icons/issues/46

via @anselmbradford 

> This is certainly not a priority, but I just wanted to note for reference this icon set I saw https://github.com/icons8/flat-color-icons that delivers the icons as SVG so colors can be included. Wouldn't it be sweet if cf-icons included an option for colors? Browser support is all evergreens plus IE9+ w/ hacks.

**Comment by jimmynotjim** [comment]
We did this!!!
