### ISSUE TITLE
Documentation site broken in Windows 7, IE8

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#221]
Reported in https://github.com/cfpb/cf-icons/issues/54

This is what the demo pages shows in Sauce Labs:

<img width="162" alt="screen shot 2015-09-29 at 5 51 10 pm" src="https://cloud.githubusercontent.com/assets/702526/10179241/b4aa0eb8-66d2-11e5-8866-e6ae6649e958.png">

**Comment by anselmbradford** [comment]
Icons don't appear to be broken:

![screen shot 2017-07-27 at 12 58 47 pm](https://user-images.githubusercontent.com/704760/28682547-5d2f5b14-72cb-11e7-92ed-c14df178ed61.png)


…but the documentation site is busted in IE8 overall:
![screen shot 2017-07-27 at 12 56 14 pm](https://user-images.githubusercontent.com/704760/28682522-45c6b17a-72cb-11e7-82f1-922929c2fb61.png)

![screen shot 2017-07-27 at 1 01 53 pm](https://user-images.githubusercontent.com/704760/28682679-d062acf8-72cb-11e7-97b6-0cd707eec74d.png)

**Comment by jimmynotjim** [comment]
Icons have been replaced with svg icons, this is no longer a valid issue.

**Comment by anselmbradford** [comment]
Looks like the docs site (and GH overall) isn't accessible at all anymore in IE8, probably because of SSL. Good riddance!
