### ISSUE TITLE
[cf-forms] Update input with button to handle more than one adjoining button

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#224]
via @anselmbradford in https://github.com/cfpb/cf-forms/issues/29

> See this pen as an example http://codepen.io/anon/pen/EavvZj
> 
> ![screen shot 2015-02-03 at 4 59 28 pm](https://cloud.githubusercontent.com/assets/704760/6030528/0cef7bc6-abc6-11e4-8666-e0639e64fdcd.png)

**Comment by jimmynotjim** [comment]
@anselmbradford Did this pattern ever emerge as necessary? If there is no use case I think we shouldn't put in extra work supporting it.
