### ISSUE TITLE
[cf-forms] deprecate warning + success alert style at the form field level

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#228]
Original issue at https://github.com/cfpb/cf-forms/issues/39

Some pages (such as retirement) make use of the field-level warning style, which has been deprecated in the latest Design Manual standards (see https://github.com/cfpb/design-manual/issues/346).

![screen shot 2015-09-25 at 12 08 51 pm](https://cloud.githubusercontent.com/assets/702526/10105713/32809b52-637e-11e5-8079-e564410828f6.png)

Another deprecated field-level alert is the `.success` style:

![screen shot 2015-09-25 at 12 13 10 pm](https://cloud.githubusercontent.com/assets/702526/10105820/cd121c18-637e-11e5-989c-adef1d423aa5.png)

In order to update cf-forms to reflect the standards accurately, we need a plan for replacing these elements with a standards-compliant version. Updates would need to be made to the following repos:

* cf-forms
* capital-framework `cf-theme-overrides.less`
* generator-cf `cf-theme-overrides.less`

@sonnakim

**Comment by jimmynotjim** [comment]
@KimberlyMunoz this was completed on the Capital Framework side by #403 correct?

**Comment by KimberlyMunoz** [comment]
Yep
