### ISSUE TITLE
[cf-forms] Text input fields

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#229]
Via @cfarm in https://github.com/cfpb/cf-forms/issues/36

> @sonnakim Tracking development of the form fields here.
> 
> Wireframe:
> ![screen shot 2015-09-15 at 5 58 00 pm](https://cloud.githubusercontent.com/assets/702526/9891291/5b108be8-5bd3-11e5-8d9a-393b5dc218bb.png)

**Comment by jimmynotjim** [comment]
This was hashed out in v4 and can be closed.
