### ISSUE TITLE
[cf-typography] Link lists have cursor:text not cursor:pointer style

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#231]
Reported by @anselmbradford in https://github.com/cfpb/cf-typography/issues/32

> Hover over the link lists [in the docs](https://cfpb.github.io/cf-typography/docs/#horizontal-list-modifier). They have a `cursor:auto` style, which appears to be ending up as `cursor:text` when the expectation would be that the links are `cursor:pointer` I would think?

**Comment by jimmynotjim** [comment]
Fixed in v4
