### ISSUE TITLE
[cf-expandables] Expandable groups should have a top-border when a header is absent

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#235]
via @anselmbradford in https://github.com/cfpb/cf-expandables/issues/45

When an expandable group has a header there is a horizontal rule between the header and the expandable items. However, when a header isn't used the horizontal rule is gone:

With header:
![screen shot 2015-04-03 at 12 34 00 pm](https://cloud.githubusercontent.com/assets/704760/6985127/e250a866-d9fd-11e4-8e97-9059e4dd54db.png)

Without header:
![screen shot 2015-04-03 at 12 34 10 pm](https://cloud.githubusercontent.com/assets/704760/6985128/e5d2dfc2-d9fd-11e4-9ae1-a1fe8ffcc5b3.png)

The expandable group should keep the horizontal rule at the top whether a header is present or not, so that it looks like:
![screen shot 2015-04-03 at 12 36 46 pm](https://cloud.githubusercontent.com/assets/704760/6985143/1ee08cb0-d9fe-11e4-8f59-6ae6fce0d5e1.png)

**Comment by anselmbradford** [comment]
Header is no longer part of the stack in [GHE]/github-enterprise-assets/0000/0160/0001/6749/b5e55d5e-82c1-11e5-91a7-244e59e22ddd.png so this issue will no longer be applicable when atomic design specs make it over here.

**Comment by jimmynotjim** [comment]
Fixed in v4
