### ISSUE TITLE
[cf-expandables] Better handling of missing dependencies

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#237]
via @himedlooff in https://github.com/cfpb/cf-expandables/issues/44

It's not totally clear that you need to wire up `jquery.easing` in order to use this. It would be nice if the README explained this OR it would be cool if the JS would not break if `jquery.easing` wasn't available. Maybe something like:

```
if jquery.easing
    slide w/ easing
else
    just do normal linear sliding that is default to jquery
    maybe throw a useful error that says jquery.easing is missing?
```

**Comment by Scotchester** [comment]
Atomic expandable (coming very soon) doesn't require jQuery Easing.
