### ISSUE TITLE
[cf-expandables] Click Show/Hide creates animation queue

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#238]
via @sephcoster in https://github.com/cfpb/cf-expandables/issues/53

> I would suggest that multiple clicks on show/hide should perform only a single toggle rather than adding an animation event to the queue. Current behavior allows multiple clicks which are then executed in sequence which could be confusing to users that double-click or click multiple times. I'll look into it.

@sebworks is looking into this.

**Comment by jimmynotjim** [comment]
I believe this is also fixed in v4 cc @mistergone can you confirm?

**Comment by jimmynotjim** [comment]
Bump @mistergone

**Comment by anselmbradford** [comment]
Related to https://github.com/cfpb/capital-framework/issues/536

**Comment by jimmynotjim** [comment]
Fixed in v4.
