### ISSUE TITLE
[cf-expandables] Content should be fully shown and show/hide markers should be hidden w/o JS

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#239]
https://github.com/cfpb/cf-expandables/issues/55

When JavaScript is off, a user should be able to read everything in the expandable and the show/hide markers should be hidden.

@anselmbradford has a working version of this at https://github.com/cfpb/cfgov-refresh/pull/1134

**Comment by jimmynotjim** [comment]
This is fixed in the v4 update to cf-expandables.
