### ISSUE TITLE
Scoped npm packages

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#240]
It might make sense to scope all CF components to `@cf` or `@capital-framework` in npm. See https://docs.npmjs.com/misc/scope

I'm not convinced it's necessary or useful but it's something to look into.

**Comment by contolini** [comment]
Backlogging this. Scoping CF makes sense but is not too important.

**Comment by jimmynotjim** [comment]
This is done, yeah @contolini

**Comment by Scotchester** [comment]
Agreed in 7/15 meeting that there's no value to be gained here.
