### ISSUE TITLE
[VZ] Vision / roles for upcoming CF improvements

### ISSUE THREAD

**Issue by cfarm** [cfpb/capital-framework#241]
I called a meeting with the following folks to talk about vision and roles for planning the upcoming CF improvements that we've already started through our FEWD standards meetings.
## Background
- @virtix asked @Scotchester, @jimmynotjim, @KimberlyMunoz, and @cfarm to spend time improving CF and its adoption.
- @ascott1 has made CF/Voltrazord the focus of the FEWD meetings now that we've got [front-end standards 1.0](https://github.com/cfpb/front-end).
- @Scotchester and @contolini have been the historical creators and maintainers of Capital Framework.
  So, how do we coordinate all of our time most effectively and enjoyably to get work done?
## Agenda
- How do we want to divvy up the work for Capital Framework improvements moving forward? 
- What do you see as your role in improving Capital Framework? What do you want to work on?
- How do we approve changes/pull requests?
- How do we delegate work amongst FEWDs?
- What's the vision for the future of Capital Framework? This will guide our decisions on the above questions + technical changes.
### What do you see as your role while working on CF?

@cfarm - improve the developer experience when using CF in our projects and referring to documentation so we can find what we need and easily identify gaps
@jimmynotjim - wants to get code pattern coverage to a place where we have stuff we can all use confidently.
@KimberlyMunoz  - wants to make it easier for _everyone_ to contribute changes to CF
@contolini - wants to make it easier to contribute and so people don't just complain but actually fix stuff when they have a problem.
@ascott1 - make it one work stream to add new UI components to your project WHILE adding it to Capital Framework
@Scotchester - vision: minimize disruption to project teams when using/contributing to CF. Role: coordinate changes to Capital Framework, spend more of his time on this, set priorities, keep backlog updated.
  @Scotchester's proposed focus areas for individual contributors: accessibility, js, build process, html/markup, documentation + community engagement. 
 Discussion on assigning these to specific people brought up the following concerns: 
- Limits our contributions and potential for making improvements.
- Could be a blocker if we wait only for certain people to work on certain areas. What happens if those people are out?
- Can we make these our focus areas/priorities for everyone instead of assigning each area to a specific person? That way we are all responsible.
- Risk of not having a focus for individual contributors: 'everyone else can do it' attitude so nothing ends up getting done. 
  - Can we solve this problem with a Code Review process? 
  - And with delegating during sprint planning at FEWD Friday meetings?
## Code Review workflow
- Contributors assign PR to specific reviewer from above folks- based on 'focus areas' ? or just who is available?
- Time limit: PR needs reviewing in 1 week or gets self-merged. :trollface: 
## Vision

We need some vision statements about how we want CF to work on a high level and long-term. These will guide our decisions around priorities and implementation.
- Each of us contributes to vision based on the following focus areas and posts in this thread, we'll add to the readme for guiding us during FEWD meetings.
  - [ ]  @KimberlyMunoz - accessibility vision
  - [ ] @contolini - js + build process
  - [ ] @jimmynotjim - html/markup lead
  - [ ] @ascott1 - FEWD user experience
  - [ ] @cfarm - documentation + community engagement. 
## Totally unrelated update + discussion on the one repo changes to CF.

@contolini demoed his one repo changes to get feedback. He'll demo for everyone else at FEWD Friday - will present the contributing workflow & the publishing changes workflow.

**How it works** 
- Components have been moved to the `capital-framework` repo and maintain their existing structure with src files, plus a parent directory contains a new markdown file for documenting HTML snippets + you can add a screenshot there too.
- Anything merged to master will get published to NPM by Travis for each component. master will always be the latest releases. Each component gets automated contributing + license docs, readme, etc
- With voltrazord we will publish the whole CF github repo as one bower package, for use in things like design manual. currently they are individual packages for each component and that is going away for time being.
- @contolini will post some notes to Github (including todos/next steps for other FEWDs to pick up) and share the link so @ascott1 and @cfarm can work off his usage.md file to produce docs. line 32 of template.js gulp script - produces the markdown file and compiles to usage.html template
- @contolini is out next week. so if you have questions about how this stuff works ask him this week!!!!!!!!!

**Comment by jimmynotjim** [comment]
Had a thought on the Code Review workflow. If we plan sprints well enough it should be a lot easier to know when to expect PRs and what the subject will be. Bug fixes will always come up, but new features should be added to a backlog and prioritized before work begins.

On that note, @contolini can you make sure to leave us with a prioritized list before you take off so we can do some planning/assigning next week?

**Comment by contolini** [comment]
@jimmynotjim Roger wilco. There will still be lots of juicy work to do.

**Comment by cfarm** [comment]
My first stab at some ~vision statements~ :crystal_ball: 

### Vision for documentation 

Capital Framework documentation is easy to navigate, code snippets have clear use-cases and examples, and developers can update the documentation quickly and easily in one place alongside their changes to the codebase.

### Vision for community engagement
Internal:
Capital Framework fulfills the needs of CFPB developers to quickly build and customize websites and code patterns so that we can focus on serving performant and usable websites to consumers, customers, and internal partners.

External:
needed

**Comment by cfarm** [comment]
also here are our Core values to help with the visioning https://github.com/cfpb/front-end#our-core-values

**Comment by jimmynotjim** [comment]
I kind of forgot about this. We should revisit it at March (January might be too soon) Regroup and see how we're doing and where we'd like to improve.
