### ISSUE TITLE
Updated docs initial proposal

### ISSUE THREAD

**Issue by ascott1** [cfpb/capital-framework#242]
## What is this?

This is a proposal for how we might better integrate our documentation into the cfpb.github.io/capital-framework site. The format of these docs is not that dissimilar from the current docs, but the design and proposed integration are different.

## Design & content

The goal would be to move the component documentation into the site itself. This would bring it more visually in line with the site, give us more control over the documentation, and make it easier to navigate between component documentation:

This might look something like:

![screen shot 2015-11-10 at 4 10 12 pm](https://cloud.githubusercontent.com/assets/212533/11075870/94316438-87c5-11e5-8e41-ac6a91908957.png)

**The basic structure:**

- Introduction with an overview of the component
- Link to the component(s) source (this would be the sub-directory in the cf-repo)
- Demo of the pattern
- copy and paste-able markup
- additional usage notes

I think we should also aim to use the expanded navigation pattern to make it easier to navigate to sub-headings within each componet. Here's what that pattern looks like on [cf.gov](http://www.consumerfinance.gov/library-resources/)

![screen shot 2015-11-10 at 4 11 30 pm](https://cloud.githubusercontent.com/assets/212533/11075910/c7204e9a-87c5-11e5-8311-2a05f6d2b2b7.png)

The type of sub nav pattern is also used by the [US Web Design Standards](http://uspto.github.io/designpatterns/1.x/docs/index.html) and [Bootstrap](http://getbootstrap.com/components/#btn-groups)

## Technical details

In @contolini's rearchitecture of Capital Framework, each component will contain a manually maintained [usage.md](https://github.com/contolini/capital-framework/blob/voltrazord/components/cf-typography/usage.md) file. This would move the documentation out of the LESS comments and into a separate markdown file, which would be easier and cleaner to maintain than the current implementation. We can then consume that content using something like Jekyll's `{% include %}`

## Pros

- Easier to maintain the markdown file than Topdoc style comments within Less
- Does not require a major reinvention of the docs
- Easier navigation between docs
- Easier navigation within component docs
- Clearer explanation of what each component is

## Cons

- Continues the separation of CF docs from the design manual
- Will default to displaying the components in CFPB style (which currently is not the default)
- Continues the architecture of component based navigation, which may make it harder to find things

<br>
<br>
Thoughts?

**Comment by ascott1** [comment]
I also think that more attention should be paid to how we organize the component list in the navigation. I think we should start with `cf-core` and `cf-typography` and then build up based on capabilities. Here's how I've organized it in my brain. Discussion of this may be best moved to another issues if there is interest:

- cf-core
- cf-typography
- cf-forms
- cf-tables
- cf-buttons
- cf-icons
- cf-expandables
- cf-grid
- cf-layout

**Comment by KimberlyMunoz** [comment]
I think buttons and icons should go near the top because they both are dependencies of cf-forms and other repos, but that logically makes sense to me.

**Comment by contolini** [comment]
:+1:

**Comment by stephanieosan** [comment]
There's also a crew of UXers working on organization and content strategy for the design manual. It might make sense to have one of them peek over here and provide any suggestions based on how they're reorganizing over there.

**Comment by cfarm** [comment]
I'm meeting with @marteki to talk about the design manual work today

**Comment by Scotchester** [comment]
[Hopefully this project will get picked up at the Hackathon.](https://github.com/cfpb/hackathon/issues/33) We'll revisit at the CF meeting in two weeks to see if anything more needs to be done.

**Comment by jimmynotjim** [comment]
Copied from #197
> Didn't know which issue was best for this, but just came across MailChimp's Doc site and a few things I think we could borrow. First is breaking apart the more friendly guides and the more technical docs. This would make the project much more approachable to new users while still allowing seasoned users to find code details. Second is the playground. Hosting a live playground on CodePen and embedding them into our site would allow anyone to test out the project, or even just a component, without having to dive in and build it locally, again, making it much more approachable to new users.

**Comment by Scotchester** [comment]
End of Sprint 1 update: @ascott1 hasn't had time to work on it.

We intend to break this into smaller subtasks. Stay tuned!

**Comment by Scotchester** [comment]
Semi-related: @jimmynotjim started work on filling out the `usage.md` files with a lot of the guidance that used to live in our Topdoc docs. Will create a new issue for each component to be tackled separately.

**Comment by Scotchester** [comment]
Subtasks:
- [ ] Set up importing of `usage.md` files into CF docs site pages.
- [ ] Bring in those files as they are completed on a rolling basis.
- [ ] User test the docs (nuBEWDs, UXers who code).
- [ ] Set up new issues to track UX improvements.
