### ISSUE TITLE
[VZ] Git branching model

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#248]
Voltrazord is in its final stages. Here's my proposal for CF contributions going forward. For background, please skim: http://nvie.com/posts/a-successful-git-branching-model/

#### TL;DR

 - Don't touch master. All PRs should be opened against "canary", the staging branch.
 - Don't use forks anymore. To edit CF, create a new branch locally, make your changes, and then push that branch directly to cfpb/capital-framework. Open a PR to bring your feature branch into canary.

#### Two permanent branches

- **master** is production-ready code. It should always be identical to the latest release in npm and the latest git tag.
- **canary** is the staging branch. It is periodically merged into master when we're confident in its changes.

When new code enters **master**, Travis CI automatically builds, tags and publishes it to npm.

##### "I want to change the buttons component"

1. `git checkout -b doing-something-with-buttons canary`
1. Edit `/src/cf-buttons/src/cf-buttons.less` however you want.
1. Increment the version number in `/src/cf-buttons/package.json`. Don't touch the version number in `/package.json`.
1. Describe your changes in the "Unreleased" section of `/CHANGELOG.md`
1. `git commit -am "describe your commit"`
1. `git push upstream doing-something-with-buttons` (Assuming `upstream` == `cfpb/capital-framework`)
1. Go to https://github.com/cfpb/capital-framework and open a pull request to merge `doing-something-with-buttons` into `canary`

##### "I want to make a non-component change to CF (e.g. update the README or tests)"

Same as above but increment the version number in `/package.json`.

##### "Oh crap there's a huge bug in the latest release"

Same thing as above but work directly from master.

1. `git checkout -b fix-horrible-thing master`
1. Edit whatever components.
1. Increment version number(s) in whatever components where edited.
1. Describe your changes in the "Unreleased" section of `/CHANGELOG.md`
1. `git push upstream fix-horrible-thing`
1. Go to https://github.com/cfpb/capital-framework and open a pull request to merge `fix-horrible-thing` into `master`

@cfpb/front-end-team-admin

**Comment by contolini** [comment]
I was intentionally overly-verbose above. I assure you it's not as complicated as it seems. I can go over it on a future call.

**Comment by awolfe76** [comment]
:+1: - nice work!

**Comment by KimberlyMunoz** [comment]
:+1: This is very similar to how v1 has been using the flapjack branch and will be a huge improvement to how we manage releases right now.

**Comment by Scotchester** [comment]
Makes sense to me! :+1:

**Comment by contolini** [comment]
Seems like this has been working well. If that changes we can reopen this thread.
