### ISSUE TITLE
[cf-forms] input-with-btn height between button and input is wrong

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#261]
Default input-with-btn gap and rounded corners removed to show that button is slightly taller than input: 
![screen shot 2016-01-14 at 3 34 32 pm](https://cloud.githubusercontent.com/assets/704760/12337477/4d7e325a-bad8-11e5-8e3a-ed1772167a3c.png)

Probably due to change in font-size on button text.

**Comment by jimmynotjim** [comment]
Fixed in v4
![image 2017-01-12 at 2 41 11 pm](https://cloud.githubusercontent.com/assets/1280430/21907450/3c205562-d8d5-11e6-9133-b152b2afd19b.png)
