### ISSUE TITLE
Get docs site back to minimum level of correctness

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#262]
The docs site is now out of date in several significant ways. This should be corrected before we go through with a complete docs overhaul.

- [x] No more Bower
- [x] app.js -> main.js
- [x] Option to use Gulp
- [x] Replace Contributing section temporarily with content from capital-framework README
- [x] Create zip file of current latest release and upload

Plus anything else you find.

**Comment by ascott1** [comment]
Done by @contolini as part of #266.
