### ISSUE TITLE
[cf-core] Complete usage.md

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#273]
Fill it out with usage guidance akin to what was found in [the older Topdoc docs](https://cfpb.github.io/cf-core/docs/).

**Comment by contolini** [comment]
@jimmynotjim Throw a sentence at the top of the file mentioning cf-core is consumed by all other components but not one you'll want to use on its own. Unless that's not true. Then ignore everything I just wrote.

**Comment by jimmynotjim** [comment]
@contolini missed this note before. I think there are use cases for core without any components, and we may even have projects currently working that way. @Scotchester might know.

**Comment by Scotchester** [comment]
I don't think anything uses it without _any_ other CF components, but a sentence explaining cf-core's general role  might still be good.
