### ISSUE TITLE
[cf-buttons] Complete usage.md

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#274]
Fill it out with usage guidance akin to what was found in [the older Topdoc docs](https://cfpb.github.io/cf-buttons/docs/).

**Comment by contolini** [comment]
@cfarm I think you were out during our `usage.md` party. Do you have time to update `cf-buttons`?

**Comment by cfarm** [comment]
werking.

**Comment by cfarm** [comment]
done https://cfpb.github.io/capital-framework/components/cf-buttons/ (I did nothing this is done already. I can maybe add some navigation?)

**Comment by cfarm** [comment]
i added some navigation
