### ISSUE TITLE
[cf-expandables] Complete usage.md

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#275]
Fill it out with usage guidance akin to what was found in [the older Topdoc docs](https://cfpb.github.io/cf-expandables/docs/).

**Comment by anselmbradford** [comment]
Would https://github.com/cfpb/capital-framework/pull/284 be the best reference for updating this issue?

**Comment by Scotchester** [comment]
No, I think this branch that Jimmy started working on would be the best thing to reference: https://github.com/cfpb/capital-framework/compare/usage-update
