### ISSUE TITLE
[cf-grid] Complete usage.md

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#277]
Fill it out with usage guidance akin to what was found in [the older Topdoc docs](https://cfpb.github.io/cf-grid/docs/).

**Comment by Scotchester** [comment]
Pushed an update to the `usage.md` branch.

**To do:** Figure out how/if we can get the grid examples rendering on the page.

**Comment by contolini** [comment]
@Scotchester push yer stuff up.
