### ISSUE TITLE
[cf-layout] Add border to Featured Content Module

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#283]
After merging #260 into our project, we have a lot of missing borders where we have `border__border` and `border__flush`, which was how we added borders to the FCM. The borders should be added to the FCM itself.

![image](https://cloud.githubusercontent.com/assets/1860176/13083255/36040a6c-d4a2-11e5-9f70-93e0097fac38.png)

**Comment by Scotchester** [comment]
Is this viewable on one of our dev servers?

**Comment by KimberlyMunoz** [comment]
Not until it makes it to refresh, you can see something like it on <flapjack>/the-bureau. Otherwise, you have to pull down the project and create an FCM to see it.

**Comment by jimmynotjim** [comment]
The solution seems to be to break apart the `block` and the FCM. I realize now combining the two on a single element was shortsighted. Wrapping the FCM in the block and adding the border to the base FCM styles fixes all the issues.

**Comment by KimberlyMunoz** [comment]
Should I close this issue or rename it to "Add border to FCM"?

**Comment by jimmynotjim** [comment]
Renaming it seems fine, the block changes are in our project specifically, but anyone that's used the FCM might have a similar situation.

**Comment by jimmynotjim** [comment]
@Scotchester looks like this is still an issue in [prerelease-ver-4](https://github.com/cfpb/capital-framework/blob/prerelease-ver-4/src/cf-layout/usage.md#featured-content-module)

![screen shot 2017-01-12 at 2 32 53 pm](https://cloud.githubusercontent.com/assets/1280430/21907153/04957740-d8d4-11e6-8849-929142609fdb.png)

Do you want to try and fix it before we release?

**Comment by anselmbradford** [comment]
Is this fixed?

**Comment by Scotchester** [comment]
Yep!
