### ISSUE TITLE
Create grunt-capital-framework task to aid in integration with existing projects

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#29]
Because integrating the framework's build process (i.e., its Gruntfile) with an existing project's build process could be very messy.

It also ensures that updates to the framework's build process don't need to be manually integrated into the project's build.

Ultimately, this should make the integration step very simple: adding a single new Grunt task to the project's Gruntfile and setting options to fit the project's needs.

Inspiration:
- https://github.com/Modernizr/grunt-modernizr
- https://github.com/topcoat/grunt-topdoc

**Comment by contolini** [comment]
Related to #151.

**Comment by Scotchester** [comment]
I think this is no longer needed. Existing projects are more likely to be (are being) rebuilt from scratch, rather than bolting on CF.
