### ISSUE TITLE
Exploring security best practices with npm

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#303]
In light of recent events, do we need to take any action to protect ourselves from broken dependencies or from hijacking?

Definitely explore [shrinkwrapping](https://docs.npmjs.com/cli/shrinkwrap).

**Comment by KimberlyMunoz** [comment]
We're shrinkwrapping now

**Comment by Scotchester** [comment]
Continues in #312

**Comment by contolini** [comment]
shwinckwap
