### ISSUE TITLE
Use .gitattributes to avoid merge conflicts in CHANGELOG

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#304]
Perhaps this technique will reduce the number of PRs that have to be updated before being mergeable?

http://krlmlr.github.io/using-gitattributes-to-avoid-merge-conflicts/

**Comment by jimmynotjim** [comment]
The "Update" section of this post verifies https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/

**Comment by marteki** [comment]
FPO has been using it successfully on both the `college-costs` and `retirement` repos. Merge conflicts due to the CHANGELOG have gone to nil.

**Comment by jimmynotjim** [comment]
@marteki Score, thanks for the confirmation
