### ISSUE TITLE
Create releases with GitHub API/Gulp?

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#31]
As we want to distribute zip files for each release, we should think about using Grunt to create the releases via the GitHub API and eliminate the need to upload the file through the web interface.

This might leverage an existing task like [grunt-release](https://github.com/geddski/grunt-release), or it could be an extension of [grunt-cfpb-internal](https://github.com/cfpb/grunt-cfpb-internal). I probably favor the latter.

**Comment by Scotchester** [comment]
I think this might still be worth doing. Renaming to reflect that CF is now built with Gulp, and moving out of VZ milestone.

**Comment by jimmynotjim** [comment]
This has been automated, closing.
