### ISSUE TITLE
Absolute URLs broken on github.io site

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#322]
- Visit https://cfpb.github.io/capital-framework/getting-started/
- Click `generator-cf` or `Compiled source` and note URL is mangled.

Seems to need adjustment to the logic in https://github.com/cfpb/capital-framework/blob/gh-pages/_includes/section-nav.html

**Comment by KimberlyMunoz** [comment]
The links on the navigation of contributing also need fixing. 

https://cfpb.github.io/capital-framework/contributing/

**Comment by Scotchester** [comment]
Done!
