### ISSUE TITLE
Docs need some general cleanup and styling fixes

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#325]
All of the component usage docs have been updated and are in much better shape. Time to polish them up a little bit.
- [x] Several pages have broken HTML examples, probably from simple malformed HTML
- [ ] Headings following code blocks could use more top margin
- [ ] Give each page a table of contents at the time that links down to that page's subsections
  - Perhaps style it in a nice little box or something
- [ ] Get Less syntax highlighting working?

**Comment by Scotchester** [comment]
@mistergone to check in on this when he's back in two weeks.

**Comment by KimberlyMunoz** [comment]
Talked with Chuck today and since he's on two teams right now and I've been working in the documentation, I'll take this on.

**Comment by KimberlyMunoz** [comment]
This is a huge task, and will touch a lot of the same stuff as the Atomic work. I talked with @ascott1 about priorities and atomic work will be ranked higher for the time being.

**Comment by jimmynotjim** [comment]
Docs:

- [ ] cf-core
- [ ] cf-icons
- [ ] cf-buttons
- [ ] cf-forms
- [ ] cf-grid
- [ ] cf-layout
- [ ] cf-typography
- [ ] cf-pagination
- [ ] cf-expandables
- [ ] cf-tables

**Comment by jimmynotjim** [comment]
@KimberlyMunoz are there any others in-progress besides cf-tables?

**Comment by KimberlyMunoz** [comment]
Nope, this is on hold until after atomic work is done.

**Comment by jimmynotjim** [comment]
@KimberlyMunoz I was going to try and get through what's left rather than start another atomic component. Figured we should divvy up the work tomorrow during the call (or after via chat if we run out of time).

**Comment by jimmynotjim** [comment]
Pretty sure we've addressed all of these within prerelease-ver-4. See #438
