### ISSUE TITLE
Set up linting

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#33]
We need both CSS and JS linting. There is an open question on when to run them. The options we are considering are:
1. Running during each `grunt compile`
2. Running only on pre-commit.

**Research**
- Grunt linting tips  
  [Eliminating Code Smell with Grunt](http://flippinawesome.org/2013/12/02/eliminating-code-smell-with-grunt/)
- Pre-commit tests  
  [Setting up pre-commit tests with Git](http://dduvnjak.pw/adding-pre-commit-tests-with-git)

**Comment by contolini** [comment]
We have ESLint set up with the generator. Still need to consider CSS linting.

**Comment by KimberlyMunoz** [comment]
I talked with @anselmbradford about LESS linting

We found: 
- https://www.npmjs.com/package/gulp-lesshint
- https://github.com/postcss/postcss-bem-linter 
- https://www.npmjs.com/package/stylelint

**Comment by jimmynotjim** [comment]
Completed in #675
