### ISSUE TITLE
Can we add the testing checklist to CFPBot PRs?

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/capital-framework#335]
[We have a great testing checklist.](https://cfpb.github.io/capital-framework/contributing/testing-snippet.html) We should include it in our release PRs to make sure we're running through the browser checklist before a (major) release.
## Current behavior
- This is what a CF Release PR looks like: 
  https://github.com/cfpb/capital-framework/pull/334
## Expected behavior
- It looks like that but has a section with the [testing checklist here](https://cfpb.github.io/capital-framework/contributing/testing-snippet.html)

**Comment by contolini** [comment]
An excellent idea.

**Comment by anselmbradford** [comment]
@contolini This issue is no longer applicable with the move to lerna, correct?

**Comment by Scotchester** [comment]
@anselmbradford Doesn't seem like it to me.
