### ISSUE TITLE
[cf-tables] Tables can't be sorted down on page load

### ISSUE THREAD

**Issue by niqjohnson** [cfpb/capital-framework#339]
Tables can't be sorted down on page load.
## Current behavior

Sortable tables like this:

``` html
<table class="table__sortable">
  ...
    <th>
      <button class="sortable sortable__start-down">Column Name</button>
    </th>
  ...
</table>
```

are not sorted on page load. However, replacing `sortable__start-down` with `sortable__start-up` will correctly sort the table on page load.
## Expected behavior

The table should sort down by the indicated column on page load. 
## Steps to replicate behavior
1. Create a sortable table with one column marked as `sortable__start-down` on a page.
2. Load the page.
3. Note that the table is not sorted until you click on a sortable column.
## Fix

I think this should be a quick fix. Right now, https://github.com/cfpb/capital-framework/blob/canary/src/cf-tables/src/cf-tables.js#L32 is

``` js
$table.find( '.sortable__start-up, .sortable__start-up' ).click();
```

Pretty sure that should be

``` js
$table.find( '.sortable__start-up, .sortable__start-down' ).click();
```

**Comment by contolini** [comment]
Good find -- having that duplicate selector there is likely a mistake. cc'ing @mistergone to confirm.

**Comment by jimmynotjim** [comment]
@mistergone is this a simple fix, or should it be backlogged till after the atomic work is completed?

**Comment by jimmynotjim** [comment]
@mistergone this was fixed with the v4 version of cf-tables correct?

**Comment by jimmynotjim** [comment]
This was indeed fixed in the v4 release and is in use in cfgov on production.
