### ISSUE TITLE
Atomic Design Workflow

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#340]
Helpful instructions and tips for converting existing components to Atomic Design Organization

**Install CF Sandbox**
1. Follow the [installation instructions](https://github.com/jimmynotjim/capital-framework-sandbox#installation).
2. Click around to ensure the local server is rendering the sandbox correctly.
3. Stop the server (ctrl+c).

**Link your component**

~~1. Navigate to the root of your component (not the CF repo)~~
  ~~`cd capital-framework/src/cf-pagination`~~

  You can now run an npm script from the root of the CF repo.
  `cd capital-framework`
~~2. Run the NPM Link command~~
  ~~`npm link`~~

  `npm run cf-link`
  To add your component to this command, edit the script in `package.json`
3. In a new tab navigate to the root of CF Sandbox

   `cd capital-framework-sandbox`
~~4. Run the component NPM Link command~~

  ~~`npm link cf-pagination`~~

  Run the same command from the root of the Sandbox repo.
  `npm run cf-link`
  Again, to add your component to this command, edit the script in this repos `package.json`
5. Run the build command

   `npm run build`
6. Start the server and check out the changes

   `npm start`

_When you’re done working on or reviewing a component, run `npm unlink component-name && npm install component-name`_

**Building your component**
1. In CF Sandbox create a new preview branch, start the server, and adjust markup as needed
   
   ``` sh
   cd /capital-framework-sandbox
   git checkout -b cf-pagination-example
   npm start
   ```
2. Checkout the v4 branch of CF
   
   ``` sh
   cd /capital-framework
   git checkout prerelease-ver-4
   ```
3. Create a new branch for your atomic component
   
   ``` sh
   git checkout -b atomic/pagination
   ```
4. Save your changes
5. When you save, CF Sandbox will build the files (may still need a manual page refresh)

**Code organization**

Both prefixing and organizing elements by their type is the easiest way to keep track of them. All elements should be prefixed by the first letter of it's type (ex `m-pagination`) and placed in a corresponding directory (ex. `/src/molecules/pagination.less`). To save yourself the trouble of moving things multiple times, we found it easiest to break up the component in it's top level stylesheet, then move each class to it's appropriate sub-directory.

**Questions**

Feel free to ask questions or post your own tips here or in the Atomic Design channel.

**Comment by jimmynotjim** [comment]
Ans and I discussed what should and shouldn't be updated to an atomic element during the workshop today. The guidelines we came up with are:

- If it can't stand on it's own as an element, for example a paragraph or list item have minimal styles added to them and don't need a class name every time they are used, but a button is more complex and so it should be atomized.
- If it's not a utility, utilities are adjustments and helpers, not elements that can stand on their own, and don't need to be atomized (another example are the layout styles, though we discussed those should probably get a `u-` prefix).

Does everyone agree, disagree, fall somewhere in the middle? I'm sure we'll discover more instances as we move along, so feel free to discuss here as that happens.

**Comment by Scotchester** [comment]
Those rules make sense on their face. As you say, I'm sure we'll come across things that are still not straightforward as we go, but we can discuss them when that happens.

I am curious, though, to know which layout styles you think should probably get a `u-` prefix.

**Comment by jimmynotjim** [comment]
Nearly everything, other than the Hero and FCM it's all layout utilities and very little is able to stand out as a component.

**Comment by jimmynotjim** [comment]
I've updated both of my PRs (https://github.com/cfpb/capital-framework/pull/326/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R29 and https://github.com/jimmynotjim/capital-framework-sandbox/pull/11/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R14) to include an automated NPM Linking script. Once those are in, it'll be easy for everyone to add their own component to the scripts and remove a lot of the manual linking pains.

**Comment by jimmynotjim** [comment]
Kim brought up two concerns in chat, that we should probably discuss a bit before (and during) Thursday's meeting.

- How do we handle dependency changes (ex who's responsible for updating all the other components button markup, how do we keep the scope tight in the buttons PR)?
- What's the priority order for updating components (ex bottom up or easiest to hardest)?

**Comment by Scotchester** [comment]
> How do we handle dependency changes (ex who's responsible for updating all the other components button markup, how do we keep the scope tight in the buttons PR)?

I think it makes the most sense for the person updating a component to also update any other component that depends on it to use the new class names.

> What's the priority order for updating components (ex bottom up or easiest to hardest)?

I'm not sure it matters, if we're going for a bit, all-at-once release of v4.

**Comment by KimberlyMunoz** [comment]
In a case like changing buttons or grid, once those get changed a lot of other stuff changes with it. Since the markup is going to be changing a lot, it probably makes sense to get stuff like atoms and utilities in first so that people using them in organisms can properly test and account for the new changes. Otherwise, the work involved with things like buttons and grid is going to hold them up so that they don't get merged.

**Comment by jimmynotjim** [comment]
We've completed this work.
