### ISSUE TITLE
Convert Featured Content Module to Atomic Design

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#342]
As part of the v4 atomic design update, convert the existing Featured Content Module to the atomic design principles. Component should be broken out into appropriate atoms, molecules, and organisms.

__How to Build an Atomic Component__

[Atomic Design Workflow](https://github.com/cfpb/capital-framework/issues/340)
[Making Sense of Atomic Design](https://about.futurelearn.com/blog/atomic-design-molecules-organisms/)

__Where to find existing Atomic Work__

- [Atomic PRs](https://github.com/cfpb/capital-framework/pulls?q=is%3Aissue+is%3Aopen+label%3A%22atomic+design%22+is%3Apr)
- [v1 atoms](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/atoms)
- [v1 molecules](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/molecules)
- [v1 organisms](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/organisms)

**Comment by KimberlyMunoz** [comment]
Related Design Manual Issues: 
https://github.com/cfpb/design-manual/issues/386
https://github.com/cfpb/design-manual/issues/351

**Comment by marteki** [comment]
Use cases determined:
* Video of people
* Animated videos
* Maps (with centered focus but needed info on the side)
* Images (with text or info needed from sides)

Questions asked, and decisions made:
* Scaling vs cropping?
  * Cropping!
* Where should we anchor where to crop from?
  * Ask in Wagtail CMS two questions: "Are you featuring a video? (If so, it'll crop from the center)." and "Are you featuring a map? (If so, it'll crop from the right)."
    * If video, anchor from center.
    * If map, anchor from lower right.
    * If anything else, anchor from lower left.
* What to do if the content included is over the character count guidelines, or the line breaks get messed up?
    * ALWAYS make the image full width :-D

**Comment by amycesal** [comment]
^ always make the image full HEIGHT. (not width)

**Comment by sephcoster** [comment]
The current recommendation from the workshop team is to do the following:

1. Create multiple Wagtail organisms / content types for selection by content editors that include:
  * Video (crop center)
  * Maps (anchor bottom right crop left)
  * Image / Default (anchor bottom left)

1. Update cf-layout to include `.less` for each of those three named atomic classes (for example: `a-fcm-video`, `a-fcm-maps` or something similar)

**Comment by contolini** [comment]
I'm out of the office next week. I unassigned myself so I don't serve as a blocker. I'll catch up when I return.

**Comment by mistergone** [comment]
https://github.com/cfpb/capital-framework/pull/386 should go a ways to addressing the recommendations here.
