### ISSUE TITLE
Convert Hero to Atomic Design

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#343]
As part of the v4 atomic design update, convert the existing Hero to the atomic design principles. Component should be broken out into appropriate atoms, molecules, and organisms.

__How to Build an Atomic Component__

[Atomic Design Workflow](https://github.com/cfpb/capital-framework/issues/340)
[Making Sense of Atomic Design](https://about.futurelearn.com/blog/atomic-design-molecules-organisms/)

__Where to find existing Atomic Work__

- [Atomic PRs](https://github.com/cfpb/capital-framework/pulls?q=is%3Aissue+is%3Aopen+label%3A%22atomic+design%22+is%3Apr)
- [v1 atoms](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/atoms)
- [v1 molecules](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/molecules)
- [v1 organisms](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/organisms)

- [x] Code
- [x] Docs
- [x] Sandbox jimmynotjim/capital-framework-sandbox#14
- [x] PR https://github.com/cfpb/capital-framework/pull/360

**Comment by KimberlyMunoz** [comment]
There's two heroes, the version on the home page and the one on the landing pages.

https://github.com/cfpb/cfgov-refresh/blob/12c7b435e10a7a8662b37452de25069c01c411a1/cfgov/jinja2/v1/_includes/molecules/home-hero.html

https://github.com/cfpb/cfgov-refresh/blob/12c7b435e10a7a8662b37452de25069c01c411a1/cfgov/jinja2/v1/_includes/molecules/home-hero.html

https://github.com/cfpb/cfgov-refresh/blob/12c7b435e10a7a8662b37452de25069c01c411a1/cfgov/jinja2/v1/_includes/molecules/hero.html

**Comment by jimmynotjim** [comment]
Ignore the home page hero, it's a one-off thing that at some point should be replaced with the standard hero if possible. This is the relevant issue for the Design Manual => https://github.com/cfpb/design-manual/issues/348. 

There is an outstanding Platform issue to make the standard hero bleed edge to edge, so there would be no gutter around photo heros such as this one.

<img width="511" alt="screen shot 2016-07-18 at 1 20 10 pm" src="https://cloud.githubusercontent.com/assets/1280430/16988479/88b17b7e-4e5e-11e6-9cf9-4a0c9cfd950d.png">

It's encouraged, but not a requirement to figure out how to make that work between both photo and illustration heros. The current issue is that the illustration canvas is cropped tight to the graphic (rather than a canvas with gutter space) and making the hero bleed edge to edge would cause that graphic lack any visual breathing room.

**Comment by ielerol** [comment]
While working on this, we discovered that if the hero text is not long enough for a full line, the text element width shrinks and the image ends up in the wrong place. The solution probably involves converting the heroes to use flexbox instead of table cells, but it's a low priority since we're unlikely to ever have too little text in a hero on the live site.

**Comment by jimmynotjim** [comment]
Scott finished it up just in the nick of time.
