### ISSUE TITLE
Convert Forms to Atomic Design

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#345]
As part of the v4 atomic design update, convert the existing Forms to the atomic design principles. Component should be broken out into appropriate atoms, molecules, and organisms.

__How to Build an Atomic Component__

[Atomic Design Workflow](https://github.com/cfpb/capital-framework/issues/340)
[Making Sense of Atomic Design](https://about.futurelearn.com/blog/atomic-design-molecules-organisms/)

__Where to find existing Atomic Work__

- [Atomic PRs](https://github.com/cfpb/capital-framework/pulls?q=is%3Aissue+is%3Aopen+label%3A%22atomic+design%22+is%3Apr)
- [v1 atoms](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/atoms)
- [v1 molecules](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/molecules)
- [v1 organisms](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/organisms)

**Comment by KimberlyMunoz** [comment]
Related Design Manual Issues:

https://github.com/cfpb/design-manual/issues/229
https://github.com/cfpb/design-manual/issues/236
https://github.com/cfpb/design-manual/issues/290
https://github.com/cfpb/design-manual/issues/346

I also did some work on v1 with updated the code Cat wrote with forms and I'll also link that in this thread.

**Comment by KimberlyMunoz** [comment]
Related v1 PRs:
https://github.com/cfpb/cfgov-refresh/pull/1199
https://github.com/cfpb/cfgov-refresh/pull/1273

**Comment by cfarm** [comment]
@anselmbradford's branch https://github.com/cfpb/capital-framework/tree/update_form_elems this contains the cfgov-refresh forms (non atomic)

**Comment by cfarm** [comment]
Here's the Design Manual latest standard for forms (yet to be merged to Design Manual master) http://cfarm.github.io/design-manual/ui-toolkit/form-fields.html

**Comment by cfarm** [comment]
I made this here PR for the select elements https://github.com/cfpb/capital-framework/pull/350

**Comment by niqjohnson** [comment]
Here's the plan for atomizing the slider shown at http://cfarm.github.io/design-manual/ui-toolkit/form-fields.html#sliders.

```
.m-slider
    .a-label
    .a-range
    .m-slider_value
```

Notes:

- `.a-label` should be the standard `h4` label used with any other form element; that's a change form what's on the draft design manual page right now
- `.m-slider_value` hasn't had any development work done yet; the idea is that there's some text (under the range handle?) that shows the current value of the input

**Comment by sonnakim** [comment]
Here's the proposal for radio buttons with large target areas
```

<fieldset class="m-fieldset">
    <div class="form-l_col
                form-l_col-1">
        <legend class="a-label__header">
            Pick an option
        </legend>
    </div>
    <div class="form-l_col
                form-l_col-1-2
                form-l-inset">
        <div class="m-large-radio-button">
            <input class="a-input"
                   type="radio"
                   name="form_id"
                   id="input_id_1">
            <label class="a-label__input"
                   for="input_id_1">
                Yes
            </label>
        </div>
    </div>
    <div class="form-l_col
                form-l_col-1-2
                form-l-inset">
        <div class="m-large-radio-button">
            <input class="a-input"
                   type="radio"
                   name="form_id"
                   id="input_id_2">
            <label class="a-label__input"
                   for="input_id_2">
                No
            </label>
        </div>
    </div>
</fieldset>
```

**Comment by KimberlyMunoz** [comment]
Hey @sonnakim, since I have to make markup changes to bring radio buttons into spec I'll take the radio buttons for now.

@anselmbradford, have you done work on this?

**Comment by KimberlyMunoz** [comment]
↪️  https://github.com/cfpb/cfgov-refresh/pull/2292
