### ISSUE TITLE
Standardize BEM naming of variables and classes

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#346]
Update the variable and class names to a more consistent use of BEM throughout the project. Underscores should be used to break up a module from it's parent.

**Correct**

 `@pull-quote_body`

**Incorrect**

`@micro-copy-text`
## Current behavior

There are a mix of naming formats 

Ex. (https://github.com/cfpb/capital-framework/blob/bc13d43a183b8b7046252c89250326b437ebd3c1/src/cf-typography/usage.md#color-variables)

```
// .pull-quote
@pull-quote_body:               #494440; // $color-gray-warm-dark
@pull-quote_citation:           #205493; // $color-cool-blue

// .micro-copy
@micro-copy-text:               #112e51; // $color-primary-darkest

// .date
@date-text:                     #112e51; // $color-primary-darkest

// .category-slug
@category-slug-text:            #112e51; // $color-primary-darkest
@category-slug-hover:           #205493; // $color-primary-darker
```
## Expected behavior
- Naming format should be consistent throughout.

**Comment by Scotchester** [comment]
I don't think this is as straightforward as you hope.

For example, `.micro-copy` and `.date` are single elements. The `-text` portion of them is not a child module. Similarly, `-hover` is not a child module.

**Comment by jimmynotjim** [comment]
I think there's plenty of room for discussion here. 

 `body` could be standardized as the label for main text colors? 

`-hover` is a state, and could then be a modifier as `__hover`?

**Comment by jimmynotjim** [comment]
I think we've addressed this where possible.
