### ISSUE TITLE
Precompiled CSS file should be run through Autoprefixer

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#348]
(so that projects not compiling the Less themselves will have better browser support)

**Comment by KimberlyMunoz** [comment]
Another issue: Do we remove any prefixes we already have in the code base?

**Comment by jimmynotjim** [comment]
Are there projects using the precompiled CSS and not importing the Less files directly?

**Comment by contolini** [comment]
> Another issue: Do we remove any prefixes we already have in the code base?

I vote yes.

**Comment by KimberlyMunoz** [comment]
> Are there projects using the precompiled CSS and not importing the Less files directly?

We offer a precompiled CSS option on our website, so we should make sure that has the same support as the Less files.

**Comment by jimmynotjim** [comment]
My question was more how do we enforce the prefixing on the less files? We could include a note in the usage doc, but once the less files leave this project, it's up to the subsequent project to ensure everything is properly prefixed.

**Comment by anselmbradford** [comment]
Question on this: What is the use case for projects to import the less file instead of importing the precompiled CSS?

**Comment by jimmynotjim** [comment]
Every project that uses the variables and mixins imports the Less files. It's really the precompiled CSS files that are an outlier.

**Comment by anselmbradford** [comment]
Ah, right, thanks @jimmynotjim

**Comment by jimmynotjim** [comment]
✋
