### ISSUE TITLE
RequireJS VS Browserify

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#35]
RE: #34, if we decide to add script dependency management what should we use?

**Comment by anselmbradford** [comment]
Has anyone looked into using a ES6 module loader polyfill? Such as https://github.com/ModuleLoader/es6-module-loader ... theoretically that's the future—e.g. a standardized module format.

**Comment by ascott1** [comment]
@anselmbradford we haven't in earnest, but I'd be really interested in doing so.

**Comment by anselmbradford** [comment]
:+1: Same here.

**Comment by anselmbradford** [comment]
Last time I thumbs up an issue ;-) j/k Related to https://github.com/cfpb/cfgov-refresh/issues/244

**Comment by contolini** [comment]
Folks have settled on Browserify.

**Comment by jimmynotjim** [comment]
cfgov-refresh has already moved on from Browserify to webpack due to single page component issues cc @anselmbradford

**Comment by contolini** [comment]
@jimmynotjim @anselmbradford Do a 30-min Dev CoP on browserify vs webpack at some point plz.

**Comment by Scotchester** [comment]
> Do a 30-min Dev CoP on browserify vs webpack at some point plz.

:+1:
