### ISSUE TITLE
Update cf-core to Atomic Design

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#352]
As part of the v4 atomic design update, convert the appropriate bits of cf-core to the atomic design principles. Component should be broken out into appropriate atoms, molecules, and organisms.

__How to Build an Atomic Component__

[Atomic Design Workflow](https://github.com/cfpb/capital-framework/issues/340)
[Making Sense of Atomic Design](https://about.futurelearn.com/blog/atomic-design-molecules-organisms/)

__Where to find existing Atomic Work__

- [Atomic PRs](https://github.com/cfpb/capital-framework/pulls?q=is%3Aissue+is%3Aopen+label%3A%22atomic+design%22+is%3Apr)
- [v1 atoms](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/atoms)
- [v1 molecules](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/molecules)
- [v1 organisms](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/organisms)

- [x] Code 
- [x] Docs
- [x] Sandbox https://github.com/jimmynotjim/capital-framework-sandbox/pull/15
- [x] PR https://github.com/cfpb/capital-framework/pull/367

**Comment by jimmynotjim** [comment]
Just adding a note to include Avenir as the base font.

**Comment by KimberlyMunoz** [comment]
https://github.com/cfpb/capital-framework/pull/367

**Comment by jimmynotjim** [comment]
Turns out closing removes it from the milestone list. Reopening till we get a chance to review the milestones.
