### ISSUE TITLE
Update cf-expandables to Atomic Design

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#353]
As part of the v4 atomic design update, convert the appropriate bits of cf-expandables to the atomic design principles. Component should be broken out into appropriate atoms, molecules, and organisms.

**How to Build an Atomic Component**

[Atomic Design Workflow](https://github.com/cfpb/capital-framework/issues/340)
[Making Sense of Atomic Design](https://about.futurelearn.com/blog/atomic-design-molecules-organisms/)

**Where to find existing Atomic Work**
- [Atomic PRs](https://github.com/cfpb/capital-framework/pulls?q=is%3Aissue+is%3Aopen+label%3A%22atomic+design%22+is%3Apr)
- [v1 atoms](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/atoms)
- [v1 molecules](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/molecules)
- [v1 organisms](https://github.com/cfpb/cfgov-refresh/tree/flapjack/cfgov/unprocessed/css/organisms)

**Comment by jimmynotjim** [comment]
CFGov Refresh Code:

 - https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/unprocessed/css/organisms/expandable.less
- https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/unprocessed/css/organisms/expandable-group.less
- https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/unprocessed/js/organisms/Expandable.js
- https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/unprocessed/js/organisms/ExpandableGroup.js

**Comment by jimmynotjim** [comment]
@mistergone how are the expandables going?

**Comment by mistergone** [comment]
@jimmynotjim - Good! I got feedback on my work on the 7th, but I was out most of this week (including the holiday), so I haven't done additional work since that feedback session.

**Comment by jimmynotjim** [comment]
The main code is merged but I just realized it's not in the sandbox. @mistergone do you have time to make sure https://github.com/cfpb/capital-framework-sandbox/tree/atomicjs-exp is all ready to go and open a PR?

**Comment by jimmynotjim** [comment]
Sandbox PR is open and available for review.
