### ISSUE TITLE
Version 4 (aka Atomic) Release

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#356]
_Components:_
- [x] cf-core
  - [x] Code
  - [x] Docs
  - [x] Sandbox
  - [x] PR
- [x] cf-buttons
  - [x] Code
  - [x] Docs
  - [x] Sandbox
  - [x] PR
- [x] cf-expandables
  - [x] Code
  - [x] Docs
  - [x] Sandbox
  - [x] PR
- [x] cf-forms
  - [x] Code
  - [x] Docs
  - [x] Sandbox
  - [x] PR
- [x] cf-grid
  - [x] Code
  - [x] Docs
  - [x] Sandbox
  - [x] PR
- [x] cf-icons
  - [x] Code
  - [x] Docs
  - [x] Sandbox
  - [x] PR
- [x] cf-layout
  - [x] Code
  - [x] Docs
  - [x] Sandbox
  - [x] PR
- [x] cf-pagination
  - [x] Code
  - [x] Docs
  - [x] Sandbox
  - [x] PR
- [x] cf-tables
  - [x] Code
  - [x] Docs
  - [x] Sandbox
  - [x] PR
- [x] cf-typography
  - [x] Code
  - [x] Docs
  - [x] Sandbox
  - [x] PR

_Sandbox:_
- [x] Add component examples
- [x] Moved to CFPB Org
- [x] Documentation updated/created as necessary

_Design Manual:_
- [x] Update code examples

**Comment by anselmbradford** [comment]
Can't build by following `npm install && npm run build` as it is looking for `atomic-component` and `classlist-polyfill`. I was able to install after manually installing those two packages.

**Comment by jimmynotjim** [comment]
@anselmbradford that's definitely weird. I'll try a fresh install today to find out what the deal is here.

**Comment by jimmynotjim** [comment]
Install issue was addressed in #427

**Comment by jimmynotjim** [comment]
Aaaaand we're done. Thanks everyone.
