### ISSUE TITLE
Do we need a Javascript framework to support Atomic Components?

### ISSUE THREAD

**Issue by sebworks** [cfpb/capital-framework#357]
As we begin to migrate components to Capital Framework it appears we might benefit from using a Javascript framework. Just wanted to gather folks input. 

React? Angular? Microframework? Roll our own?

**Comment by mistergone** [comment]
I am not a fan of framework stacks. Whatever we require in this respect, I think we could easily build internally, hopefully keeping it very small.

Angular, React, etc - for me, it always comes back to building an app on the shifting sands of proprietary skills and third-party points of failure.

**Comment by jimmynotjim** [comment]
Agreed with @mistergone, roll something ourselves that's hopefully pretty small, yet useful enough that each component can share common scripts rather than having to duplicate work across components.

**Comment by KimberlyMunoz** [comment]
This seems like something we can revisit later. We should focus on getting this release shipped, especially since we don't have many elements that require JavaScript at this point.

**Comment by jimmynotjim** [comment]
Unfortunately, it's an issue right now. There are a bunch of utilities in the expandables and multi-select components that need to get figured out to get those update to for the atomic release. Otherwise I'd agree to table it for the fall.

**Comment by KimberlyMunoz** [comment]
Having 2-3 things that require JavaScript doesn't seem to be a reason to make a decision on a a huge framework. Why the change in thinking?

**Comment by jimmynotjim** [comment]
That's why I was voting for rolling our own with just what we need. We can get started off quickly with what's required to continue working on those three components for the v4 release and then in the future only add new bits as they come up vs tons of code we won't ever need.

**Comment by sebworks** [comment]
The JS just needs to be a bit more uniform.  The CSS is already at a place where most components look very similar in terms of structure and markup. The uniformity across components makes it easier to learn, debug, and contribute to Captial Framework. It's one of the first things contained in our front-end standards:

> All code in any code-base should look like a single person typed it, no matter how many people contributed.

The conversation is also pertinent because it deals with the core utilities that will get used across components ( as @jimmynotjim  has mentioned ).   Doesn't have to be a framework though.

**Comment by KimberlyMunoz** [comment]
@sebworks, didn't you find an article that informed how you organized the new v1 expandables? Could you share that here?

**Comment by sebworks** [comment]
This is the article @KimberlyMunoz : https://gist.github.com/sebworks/1f5238091b2c818ee4f63f7b0d9b297e.

**Comment by jimmynotjim** [comment]
It definitely seems like a very basic "component framework" is going to be needed here to continue the work in the atomic components. 

 `cf-utilities` is already used, how about naming it `cf-behavior` so that it's clear it's only a dependency for components with interactive behaviors? Should it be a sub-component of `cf-core` or stand on it's own? If independent, are there complications to keep it from being duplicated when it's installed as a dependency for each of the related behavioral components?

@sebworks would you be interested in leading the work on this since you've ushered in a lot of the JS standards? Feel free to defer if you're already loaded w/ Platform work.

**Comment by sebworks** [comment]
@jimmynotjim, I am working on this and expect to have a rough draft for review tomorrow.

**Comment by jimmynotjim** [comment]
Score. I think we can close out the discussion portion and continue in the sprint task issue or PR.
