### ISSUE TITLE
Capital Framework Meeting - 7/30/2016

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#358]
__Proposed Agenda for 7/30 Meeting__

Now that we all have a starting point in Atomic Design, let's discuss our efforts to implementing that work to the project. Topics:

- Are there any questions or concerns on the [proposed Atomic workflow](https://github.com/cfpb/capital-framework/issues/340#issue-166092567)?
  - How do we handle dependency changes (ex who's responsible for updating all the other components button markup, how do we keep the scope tight in the buttons PR)?
  - What's the priority order for updating components (ex bottom up or easiest to hardest)? 
- Are there [guidelines we can follow](https://github.com/cfpb/capital-framework/issues/340#issuecomment-234014575) when doing the work?
  - How do we handle components like cf-core, cf-layout, cf-grid?
- How can we be better at contributing directly to Capital Framework rather than individual project repos?
  - How do we speed up reviews to avoid slowing down individual projects?
  - How do we make PRs smaller and easier to merge?
  - How can we further improve the workflow to make direct contribution easier?
  - When should we backlog comments from PRs?

**Comment by KimberlyMunoz** [comment]
[Also to discuss:](https://github.com/cfpb/capital-framework/issues/340#issuecomment-235337847)

>Kim brought up two concerns in chat, that we should probably discuss a bit before (and during) Thursday's meeting.

>How do we handle dependency changes (ex who's responsible for updating all the other components button markup, how do we keep the scope tight in the buttons PR)?
What's the priority order for updating components (ex bottom up or easiest to hardest)?

**Comment by jimmynotjim** [comment]
From @cfarm 

Some questions that came up at today's Capital Framework fewd working meeting:

- Do we need a product owner for capital framework? This would make sure we prioritize work and actively develop it.
- We will need a well-managed backlog so that all FEWDs can still contribute to CF as needed.
- Who are the developers who work on Capital Framework as sprint work? For now, it's Jimmy. In the future, our team proposes the Platform FEWDs do this.

**Comment by jimmynotjim** [comment]
@farmanc also brought up in chat the idea of moving toward a CF Agile team. 

I'm interested in this idea as the design manual team has the same model for their work. I think we could keep it light and async to avoid "yet another meeting" in our lives making the current bi-weekly meeting a retro since that's sort of what they have become organically.
