### ISSUE TITLE
Update Icon Font to include "NO" icon

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#409]
A new Icon Font file will be coming with a "NO" icon from @ajbush for use in the larger target radio/checkboxes.

Task

After @Dnpizarro delivers an updated icon font file update it in the repo.

**Comment by Dnpizarro** [comment]
@jimmynotjim I just sent you the link to the file.

**Comment by anselmbradford** [comment]
@jimmynotjim you have this file?

**Comment by Scotchester** [comment]
Since this doesn't seem to be a burning need, why don't we punt it until we migrate cf-icons to SVG?

**Comment by anselmbradford** [comment]
It was on the project that I've just updated to a v5 release. Do we have an issue for SVG open?

**Comment by Scotchester** [comment]
It is on the Design Ops backlog for Jimmy and me when we don't have time-sensitive project work in front of it. I think Jimmy's got a good start on it.

**Comment by jimmynotjim** [comment]
We've completed this in https://github.com/cfpb/capital-framework/pull/752
