### ISSUE TITLE
Do content_line and rule break atom overlap?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#423]
Cfgov-refresh has a rule break atom (horizontal rule line) [here](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/css/atoms/rule-break.less).
Capital Framework has a content line [here](https://github.com/cfpb/capital-framework/blob/canary/src/cf-layout/src/cf-layout.less#L216-L219).

Can these be merged? Should they both exist?

**Comment by jimmynotjim** [comment]
I never even knew this or `content_bar` existed. They don't seem like they belong in cf-layout (though neither do heros or featured content) so I'd think we should keep the `a-rule` atom and maybe add a modifier that makes it `10px` to replace `content_bar`

**Comment by Scotchester** [comment]
`content_bar` should not be considered an atom (or modified atom). It's really just a border, that we had to make its own HTML element because reasons.

**Comment by jimmynotjim** [comment]
@Scotchester do you have examples of where it and content-bar are being used? It'd be nice to know what the reasons are and justify them.

**Comment by Scotchester** [comment]
Sorry, I should have looked before commenting. Looks like `content_bar` is no longer needed. It was required when the design specs had the green border under the header moving _under_ the hero, if a hero was present.

`content_line` is used to divide the top content are from the bottom content area on a page with a breakout sidebar: http://www.consumerfinance.gov/policy-compliance/rulemaking/

**Comment by jimmynotjim** [comment]
@anselmbradford seems we have our answer, only use `content_line` if you're breaking up the `content` elem.
