### ISSUE TITLE
[cf-icons] Provide option to override font-face declaration

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#425]
`@cf-icon-path` variable in `cf-theme-overrides` allows setting the path for the webfont files. There is an edge case uncovered in [GHE]/consumer-response/032-consumer-feedback/pull/19 where a data URI needs to be used instead to embed the fonts. However, the `@cf-icon-path` variable needs to be set to an empty data URI as a hack to turn browsers from throwing an error for the missing font path to instead issuing a warning. Perhaps the [`font-face` declaration](https://github.com/cfpb/capital-framework/blob/canary/src/cf-icons/src/cf-icons.less#L30-L39) should be wrapped in a mixin with a [guard](http://lesscss.org/features/#css-guards-feature) so that an option can be passed in which would allow it not to be set at all, so that it can be set elsewhere as a data URI declaration.

**Comment by jimmynotjim** [comment]
@anselmbradford could this be resolved by Base64 encoding? Turns out we have an old discussion on that https://github.com/cfpb/capital-framework/issues/160

**Comment by jimmynotjim** [comment]
We've replaced the icon font with inline SVGs. The icon font is in the process of being deprecated and will be removed entirely in the v6 release.
