### ISSUE TITLE
Audit automated build

### ISSUE THREAD

**Issue by ascott1** [cfpb/capital-framework#428]
Audit the automated build process to ensure that it works with the v4 atomic structure.

**Comment by contolini** [comment]
Thanks for being patient while I found time to work on this! I went through all the scripts and ran them locally and they all worked as expected.

The crux of their work is building CF by simply running [`gulp build`](https://github.com/cfpb/capital-framework/blob/prerelease-ver-4/scripts/npm/prepublish/lib/build.js#L8). That command hasn't changed with v4 so no issues there. 

The [chat ops script](https://github.com/cfpb/hubot-capital-framework) that creates a pull request in a special format is much more fragile than the publishing scripts in this repo. I predict the bot will fail when trying to make a PR but that's okay -- we can look into it if/when it happens. It's not going to damage anything by opening a wonky PR.
