### ISSUE TITLE
Add notifications component

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#440]
Notifications have been [added to the Design Manual](https://github.com/cfpb/design-manual/pull/366). Post v4, add a cf-notifications component and update the Design Manual when it's ready.

**Comment by cfarm** [comment]
notification element can be ported from cfgov-refresh: https://github.com/cfpb/cfgov-refresh/search?utf8=%E2%9C%93&q=notification&type=

**Comment by cfarm** [comment]
Ans already got started https://github.com/cfpb/capital-framework/pull/560
