### ISSUE TITLE
Hero content spans the full page width

### ISSUE THREAD

**Issue by niqjohnson** [cfpb/capital-framework#443]
When I was using Capital Framework v4 to prototype the Financial Well-Being Scale, I came across a bug that causes hero content to span the full width of the page rather than being contained in the wrapper width as intended. 

## Current behavior

- The content of a hero spans the full width of the viewport at large screen sizes.

## Expected behavior

- The content of the hero should only be as wide as the wrapper at large screen sizes.

## Steps to replicate behavior

Add a hero to a page OUTSIDE of any wrapper (as I think you have to to get the background color to span the full page?), like so:

```html
<main class="content content__2-1 content__bleedbar" id="main" role="main">
    <section class="m-hero">
        <div class="m-hero_wrapper wrapper">
            <div class="m-hero_text">
                <h1 class="m-hero_heading">
                    Hero heading
                </h1>
                <p class="m-hero_subhead">
                    Hero subheading
                </p>
            </div>
            <div class="m-hero_image-wrapper">
                <div class="m-hero_image" style="background-image: url('')"></div>
            </div>
        </div>
    </section>
    <div class="wrapper content_wrapper">
        <div class="content_main ">
            ....
        </div>
        <aside class="content_sidebar o-sidebar-content">
            ....
        </aside>
    </div>
</main>
```

The contents of the hero should span the entire width of the viewport. I think this behavior is hidden in the sandbox examples because they're all contained in a wrapper.

## Screenshots

__Current__

![current](https://cloud.githubusercontent.com/assets/1862695/22566394/b0165324-e959-11e6-870e-355fca2ed2de.png)

__Expected__

![expected](https://cloud.githubusercontent.com/assets/1862695/22566399/b5dfe130-e959-11e6-9a65-bca854055e53.png)

**Comment by jimmynotjim** [comment]
@niqjohnson can you test this now that v4.3.0 is released? Thanks

**Comment by niqjohnson** [comment]
I used the same HTML as above, and the hero was only as wide as the page wrapper, as expected.

👍

**Comment by jimmynotjim** [comment]
Perfecto, thanks.
