### ISSUE TITLE
@grid_wrapper-width too large in starter project generated by Yeoman

### ISSUE THREAD

**Issue by niqjohnson** [cfpb/capital-framework#444]
When using `yo cf` to generate a starter Capital Framework project, `@grid_wrapper-width` is set to `1230px` in `cf-theme-overrides.less`.

## Current behavior

- Line 159 in the `cf-theme-overrides.less` file generated by `yo cf`, `@grid_wrapper-width` is set to `1230px`; that makes any pages designed based on the starter project 30 px wider than on cf.gov

## Expected behavior

- `@grid_wrapper-width` should be `1200px`

## Steps to replicate behavior

1. Update the Capital Framework Yeoman generator
2. `yo cf`
3. Select all the CF components and gulp as the build tool
4. Let the generator generate
5. Open up `cf-theme-overrides.less` and note that line 159 is `@grid_wrapper-width: 1230px`

## Screenshots

__Current__

![grid-wrapper-width](https://cloud.githubusercontent.com/assets/1862695/22568656/ae86e3b2-e962-11e6-8c89-efce22c41550.png)

**Comment by Scotchester** [comment]
Hey @niqjohnson, actually, generator-cf has it right. See https://[ghe]/CFGOV/platform/issues/244 and cfpb/cfgov-refresh#2707 for more info.

**Comment by niqjohnson** [comment]
Ah, gotcha, thanks.
