### ISSUE TITLE
Explore options with GH-Pages and ToC

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#446]
The Table of Contents doesn't work in the rendered Github Pages site because the urls aren't added to the headings like they are in the repo rendered markdown.

## Current behavior

- ToC links don't jump to the appropriate heading.

## Expected behavior

-ToC links should jump the page to the appropriate heading.

## Steps to replicate behavior

1. Checkout `gh-pages` branch.
2. Run `npm install` (or `npm update`)
3. Run `npm run build`
4. Run `npm start`
5. Navigate to the components in your browser and click on a ToC link

@Scotchester provided a solution using the `_config.yml`, documenting the issue so it doesn't get lost while we're all completing other work. See: https://github.com/jekyll/jekyll/issues/2690#issuecomment-51159251

**Comment by jimmynotjim** [comment]
@Scotchester it looks like `auto_ids` should be on by default and I tried adding it manually but I'm still not able to get ids in the headings.

![screen shot 2017-02-23 at 2 31 33 pm](https://cloud.githubusercontent.com/assets/1280430/23277784/cfa9e4ea-f9d4-11e6-9df8-9e6548285297.png)

![screen shot 2017-02-23 at 2 30 58 pm](https://cloud.githubusercontent.com/assets/1280430/23277757/b655da9e-f9d4-11e6-817b-1d2713db1f42.png)

**Comment by Scotchester** [comment]
I tried this and observed the same thing yesterday, too. Not sure what to do about it :\

**Comment by jimmynotjim** [comment]
This was fixed with #454
