### ISSUE TITLE
Update cf-grid width in usage doc

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#459]
## Current behavior

- https://github.com/cfpb/capital-framework/blob/canary/src/cf-grid/usage.md#variables has `@grid_wrapper-width: 1200px;`

## Expected behavior

- Per [GHE]/CFGOV/platform/issues/244 update to `1230px`.

**Comment by jimmynotjim** [comment]
This was fixed in #469 

https://github.com/cfpb/capital-framework/pull/469/files#diff-a42a8692caaf52522c4282c228ce3e86R15
