### ISSUE TITLE
Use Less extend

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#46]
> As of version 1.4, LESS supports extending a style. Extend is sort of like the opposite of a mixin. Instead of adding all the properties of a mixed-in class into a class, it adds the extending selector to the selector list for output of the extended class.

> The syntax for extend is designed to mimic the syntax of CSS pseudo-classes, and can be combined with pseudo-classes as long as any extends selectors come last.

> For example:

> ```CSS
div {
    background-color: #e0e0e0;
}
p:extend(div) {
    color: #101010;
}
```
> Will output

> ```CSS
div,
p{
    background-color: #e0e0e0;
}
p{
    color: #101010;
}
```
> As you may have noticed, this can significantly remove the amount of bloat in the output CSS compared to mixins.

> The extend selector can be used on the same line as the class selector, or it can be nested as seen in this example:

> ```CSS
.parent {
    font-size:12pt;
}
.child {
    &:extend(.parent);
}
```
> By default, extend does not include nested elements of the extended style. To do this, you must add all to the selector in the extend expression.

> For example:

> ```CSS
.a.b.test,
.test.c {
    color: orange;
}
.test {
  &:hover {
    color: green;
    }
}
.replacement :extend(.test) {
}
```
> Outputs:

> ```CSS
.a.b.test,
.test.c {
    color: orange;
}
.test:hover {
    color: green;
}
```
> But this:

> ```CSS
.a.b.test,
.test.c {
    color: orange;
}
.test {
  &:hover {
    color: green;
    }
}
.replacement :extend(.test all) {
}
```
> Outputs:

> ```CSS
.a.b.test,
.test.c,
.a.b.replacement,
.replacement.c {
  color: orange;
}
.test:hover,
.replacement:hover {
  color: green;
}
```

**Comment by contolini** [comment]
I don't fully grok the use case here so I'm going to assign this to @Scotchester because he's hella smart.

**Comment by jimmynotjim** [comment]
After more time away from Sass and heavy usage of extends, I'm starting to think mixins are better. Harry Roberts seems to agree http://csswizardry.com/2016/02/mixins-better-for-performance/. 

Since we've still not used it in projects, I think we can close this.
