### ISSUE TITLE
Look into Lerna

### ISSUE THREAD

**Issue by contolini** [cfpb/capital-framework#461]
https://lernajs.io/

> Lerna is a tool that optimizes the workflow around managing multi-package repositories with git and npm.

The [commands](https://lernajs.io/#commands) look incredibly relevant to our needs, especially `bootstrap`:

> Bootstrap the packages in the current Lerna repo. Installing all their dependencies and linking any cross-dependencies.

**Comment by anselmbradford** [comment]
Project is now on lerna since https://github.com/cfpb/capital-framework/pull/885
