### ISSUE TITLE
icon-link referenced in docs appears outdated

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#497]
`icon-link` is referenced in cf-typography usage docs. Appears that it should be updated to `.a-link__icon`?

**Comment by anselmbradford** [comment]
See https://github.com/cfpb/capital-framework/blob/canary/src/cf-typography/usage.md#links-with-icons

**Comment by jimmynotjim** [comment]
I've already fixed this in the svg icon PR https://github.com/cfpb/capital-framework/pull/752/files#diff-0110f4705a29b0617ee7e1f488720933R217. If that PR isn't reviewed by EoD it'll be merged.
