### ISSUE TITLE
Expandable accordion doesn't expand in some cases

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#536]
Bug in the accordion where it's possible to click the expandables and not have them expand. cc @mistergone as maybe he knows what's up!

## Current behavior

- Clicking the expandables repeatedly doesn't consistently expand the expandable.
![accordion-bug](https://user-images.githubusercontent.com/704760/28091168-fa72d656-665c-11e7-9979-0b95d067a66d.gif)

## Expected behavior

- Repeated clicks of the expandable does not allow the user to leave an unexpanded expandable with "hide" showing for the label.

## Steps to replicate behavior

1. Visit https://cfpb.github.io/capital-framework/components/cf-expandables/
2. Scroll to accordion example.
3. Click the first expandable repeatedly.

**Comment by Scotchester** [comment]
We decided to remove the accordion feature. See: https://[GHE]/CFPB/hubcap/issues/64

**Comment by anselmbradford** [comment]
@sebworks what was your feeling on your use-case? Is it a one-off?

**Comment by sebworks** [comment]
Ok, I'm fixing this with a new version. Obviously, I feel like the accordion has a place within capital framework.

**Comment by jimmynotjim** [comment]
> We decided to remove the accordion feature. 

[OaH has valid accordion use case](https://www.consumerfinance.gov/owning-a-home/explore-rates/), by restricting the number of open expandables the definitions stay along the side the PDF. How do want to deal with that?

cc @stephanieosan
