### ISSUE TITLE
require-dir dependency needs to be upgraded in order to use node 8

### ISSUE THREAD

**Issue by cfarm** [cfpb/capital-framework#563]
this error happens when using node 8 with this project. upgrading the `require-dir` dependency should fix it. 
 currently, the workaround is to use node 6 (i dunno why i never had node 7 but 6 works fine with this project)

```
if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (~~~~/node_modules/require-dir/index.js:97:37

```

**Comment by anselmbradford** [comment]
Chuck out your node_modules and re-install? It should be on 0.3.2 which is the compatible version for node 8 IIRC https://github.com/cfpb/capital-framework/blob/canary/package-lock.json#L4802

**Comment by cfarm** [comment]
> Note: The site doesn't build w/ Node 8 without updating require-dir and parallelshell. I switched to Node 6 and it built a-okay.

@contolini reported this too. i'll try again.

**Comment by anselmbradford** [comment]
Fixed in https://github.com/cfpb/capital-framework/pull/572 ?

**Comment by anselmbradford** [comment]
@cfarm can this be closed?
