### ISSUE TITLE
Explore moving docs site to master (and canary)

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#597]
The branching method for generating the doc site is less than ideal. To reduce the amount of cloning and scripting we've had to implement to make it work, we've discussed moving to a `/docs` directory in `master`. This would work well because

a. The source files and doc site would live in the same place, making symlinking for testing a component locally within the project unnecessary (this would still be possible for testing outside the project, like within cfgov-refresh).
b. The doc site would always be up to date with work in canary, meaning when changes are released to master, the docs site is auto-released in parallel.

The work necessary to complete this would be to 
- [ ] copy the docs site specific files to `/docs` in `canary`
- [ ] add the dependencies to `canary` (both npm and gems)
- [ ] update the gulp docs tasks for the change in file location
- [ ] release to master and cross our fingers

**Comment by anselmbradford** [comment]
What do you think about switching to a non-Ruby dependent static site generator and going with a nodejs solution such as gitbooks?

**Comment by jimmynotjim** [comment]
I'm interested in exploring that option, especially because we have to generate the entire site instead of letting GitHub do it dynamically. Have you used gitbooks before?

**Comment by anselmbradford** [comment]
I haven't really, but I've been playing around with it for this use-case. Maybe there will be time next week at regroup (haha)
