### ISSUE TITLE
Docs site isn't loading Avenir

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#599]
## Current behavior

- At some point it seems the site stopped loading Avenir as the base font.

## Expected behavior

- Docs site should load Avenir as the default font

## Steps to replicate behavior

1. open https://cfpb.github.io/capital-framework/ and observe Arial as the font-face throughout.

I think this might be related to the variables work that was recently done but I'm not sure. The stack I'm seeing is `Arial, Arial, sans-serif` instead of `Avenir, Arial, sans-serif`

**Comment by anselmbradford** [comment]
This is fixed, yeah?

**Comment by jimmynotjim** [comment]
Yep
