### ISSUE TITLE
focus and hover color variables will not work as expected in basic inputs

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#600]
We have a variable for the [color of focus and of hover](https://github.com/cfpb/capital-framework/blob/canary/src/cf-forms/src/cf-forms.less#L13-L14) in form inputs, however, radio buttons and checkboxes [combine](https://github.com/cfpb/capital-framework/blob/canary/src/cf-forms/src/molecules/form-fields.less#L75-L76) their focus and hover CSS, so setting one or the other of these two variables will not work as expected if they are different colors.

## Current behavior

- Focus and hover color are combined and share appearances, despite there being a variable for each.

## Expected behavior

- Focus and hover color should either share the same variable, or focus and hover CSS should be separated to apply each variable distinctly.

**Comment by ielerol** [comment]
I'd like to see them separated. There's a usability benefit to having focus and hover styled separately, so it would be nice to have the code set up for that in the future.
