### ISSUE TITLE
Bug: Second line of error message text should indent when text breaks to second line

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/capital-framework#626]
## Current behavior
Second line of error message is flush left. 

## Expected behavior
Second line of error message should indent so that it left aligns with the first line of text.

## Steps to replicate behavior
1.

## Screenshots

__Current__
<img width="327" alt="2a26948c-9d67-11e7-9e20-f3a9bbcdda0d" src="https://user-images.githubusercontent.com/6887128/30819427-a2a32f86-a1ec-11e7-9c70-42a8e2019808.png">

__Expected__
<img width="351" alt="33212174-9d67-11e7-9547-13550c62bee3" src="https://user-images.githubusercontent.com/6887128/30819436-a84b58e6-a1ec-11e7-83c0-074b901ef9e6.png">

**Comment by jimmynotjim** [comment]
Merged and awaiting the next deployment.
