### ISSUE TITLE
cf-unlink script updates package.json with pegged versions

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#642]
## Current behavior

- Running `npm run cf-unlink` in the gh-pages branch updates `package.json` with pegged versions, but versions are set on `latest` https://github.com/cfpb/capital-framework/blob/gh-pages/package.json#L22

## Expected behavior

- Keep `package.json` as `latest` for CF dependencies.

**Comment by jimmynotjim** [comment]
Seems that's the default behavior of `npm install` now. Probably have to specifically tell it `latest` but I'm not sure.
