### ISSUE TITLE
Changelog being wiped out on release

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#661]
## Current behavior

- More times than not the CHANGELOG.md ends up empty after a release (happened on the 4.14.1 release but not on 4.14.0).

## Expected behavior

- Changelog should be updated, not cleared on release.

## Steps to replicate behavior

1. Make a release.
2. Check changelog in canary branch. Is it blank?
(3. Manually fix it if blank.)

**Comment by anselmbradford** [comment]
Is this fixed @jimmynotjim ?

**Comment by jimmynotjim** [comment]
We're pretty sure it is, but I haven't gotten around to writing a test for it, so lets leave it open for now. I'm still worried our "fix" was just a hack.

**Comment by jimmynotjim** [comment]
This is tested and working consistently!
