### ISSUE TITLE
Hide expandable trigger labels in no-js state

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#761]
"Show"/"Hide" labels for expandables should be added with JS so they don't appear when in no-js state.

## Current behavior

- "Show"/"Hide" labels show up when JS is disabled.

## Expected behavior

- "Show"/"Hide" labels do not appear when JS is disabled.

## Steps to replicate behavior

1. Turn off JS
2. Visit https://cfpb.github.io/capital-framework/components/cf-expandables/
3. Note both expandable trigger labels show up.

## Screenshots

__Current__

![screen shot 2018-02-13 at 10 27 47 am](https://user-images.githubusercontent.com/704760/36157901-ee4aee08-10a8-11e8-9c79-937a770a3a79.png)

**Comment by jimmynotjim** [comment]
I think we used to hide them entirely with the `no-js` class. We could use that for a quick fix and add injection to the backlog for when someone has some time to spare.

**Comment by anselmbradford** [comment]
Sure 👍

**Comment by Scotchester** [comment]
In cfgov-refresh, the template has `.u-hidden` on those links by default, which gets removed by JS when initializing. One more thing to reconcile when we move cfgov-refresh to CF's expandables 😬

**Comment by jimmynotjim** [comment]
This was fixed in #787
