### ISSUE TITLE
Adjustments to checkbox and radio large target areas

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/capital-framework#771]
# Adjustments to checkbox and radio large target areas
Current implementation of [checkboxes and radio buttons with large target areas](https://cfpb.github.io/design-manual/page-components/form-fields.html#checkboxes-and-radio-buttons-with-large-target-areas) does not reflect the design intent as indicated in the DM specs and is not consistent with the logic being applied to other form components. 

#### Target area
- Border: None
- Background: Gray 10 (#e7e8e9)
#### Radio button (or checkbox)
- Border: 2 px, Pacific (#0072ce)
<img width="894" alt="screen shot 2018-02-27 at 6 15 03 pm" src="https://user-images.githubusercontent.com/6887128/36760767-2c364f36-1bea-11e8-84b4-d27f35ff1b7a.png">

#### Target area
- Border: None
- Background: Gray 10 (#e7e8e9)
- Outline: Dotted 1px, Pacific (#0072ce)
#### Radio button (or checkbox)
- Border: 2 px, Pacific (#0072ce)
<img width="881" alt="screen shot 2018-02-27 at 6 15 07 pm" src="https://user-images.githubusercontent.com/6887128/36760775-31015a2e-1bea-11e8-9fb4-4b1b6c29172c.png">

#### Target area
- Border: None
- Background: Pacific 20 (#d6e8fa)
#### Radio button (or checkbox)
- Border: 1 px, Gray 60 (#919395)
- Background: 14 x 14 px, Pacific (#0072ce)
<img width="973" alt="screen shot 2018-02-28 at 11 01 30 am" src="https://user-images.githubusercontent.com/6887128/36797906-307301ce-1c77-11e8-9a1b-90c9c3dacaed.png">

#### Target area
- Border: 2 px, Pacific (#0072ce)
- Background: Gray 10 (#e7e8e9)
#### Radio button (or checkbox)
- Border: 2 px, Pacific (#0072ce)
<img width="932" alt="screen shot 2018-02-27 at 6 14 31 pm" src="https://user-images.githubusercontent.com/6887128/36760749-1b9e9aca-1bea-11e8-91a2-87f5a4dec7d1.png">

#### Target area
- Border: 2 px, Pacific (#0072ce)
- Background: Gray 10 (#e7e8e9)
- Outline: Dotted 1px, Pacific (#0072ce)
- Outline offset: 3px
#### Radio button (or checkbox)
- Border: 2 px, Pacific (#0072ce)
<img width="904" alt="screen shot 2018-02-27 at 6 11 19 pm" src="https://user-images.githubusercontent.com/6887128/36760637-b1864c28-1be9-11e8-8f8a-4dade40999b6.png">

#### Target area
- Border: 2 px, Pacific (#0072ce)
- Background: Pacific 20 (#d6e8fa)
#### Radio button (or checkbox)
- Border: 1 px, Pacific (#0072ce)
- Background: 14 x 14 px, Pacific (#0072ce)
<img width="947" alt="screen shot 2018-02-28 at 11 09 35 am" src="https://user-images.githubusercontent.com/6887128/36798456-b252f9a0-1c78-11e8-9c0b-02ef8a3478e2.png">

## Steps to replicate behavior
1. Visit: https://cfpb.github.io/design-manual/page-components/form-fields.html#checkboxes-and-radio-buttons-with-large-target-areas

@ielerol @anselmbradford @Scotchester

**Comment by himedlooff** [comment]
I think https://github.com/cfpb/capital-framework/pull/774 closes this out no?

**Comment by anselmbradford** [comment]
Hey long time 👋 @himedlooff ! Good to see you're still watching!

**Comment by anselmbradford** [comment]
https://github.com/cfpb/design-manual/pull/624 fixes the inconsistency noted here. Can be closed in CF.
