### ISSUE TITLE
Update H4 in expandables

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/capital-framework#779]
In updating the H4 for small screens we appear to have missed expandables.  

**Related issues and links:** 
https://github.com/cfpb/capital-framework/pull/751
https://[GHE]/CFPB/hubcap/issues/65
https://cfpb.github.io/design-manual/brand-guidelines/typography.html#web-hierarchy

## Current behavior
Desktop: H4 (Avenir Next Medium 18px / 22px)
< 601px wide: H4 (Avenir Next Medium 18px / 22px)

## Expected behavior
Desktop: H4 (Avenir Next Medium 18px / 22px)
< 601px wide: H4 (Avenir Next Medium 16px / 18px)

## Steps to replicate behavior
1. https://www.consumerfinance.gov/consumer-tools/prepaid-cards/choose-the-right-card/

## Screenshots
__Current__

| Desktop | Mobile | 
| --- | --- | 
| ![5 px](https://user-images.githubusercontent.com/6887128/37124602-03907464-2237-11e8-8055-f99ef064c2c1.png)| ![10 px](https://user-images.githubusercontent.com/6887128/37124603-03a68dee-2237-11e8-99c8-a164dbcc67ba.png)|

__Expected__

| Desktop | Mobile | 
| --- | --- | 
| ![5 px](https://user-images.githubusercontent.com/6887128/37124602-03907464-2237-11e8-8055-f99ef064c2c1.png)| ![10 px](https://user-images.githubusercontent.com/6887128/37124720-67374c40-2237-11e8-86d9-cabea0d54ced.png)|

**Comment by jimmynotjim** [comment]
Clarification, are we only using h4 when they are in a group? It looks like the default styles are set that way, and https://www.consumerfinance.gov/about-us/blog/ confirms it, but I want to make sure that's not an oversight.
