### ISSUE TITLE
Rename component demo page?

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#78]
The name "demo" is a little misleading. The true intent of that page is to aid in browser testing. The word "demo" has a bit more of a real-world-usage connotation, I think. We should consider renaming it to "testing" or something similar, to reduce confusion, especially if we [start making new user-friendly demo pages](https://github.com/cfpb/cf-icons/issues/13).

**Comment by contolini** [comment]
Is this the demo page we're talking about? https://github.com/cfpb/cf-demo

**Comment by contolini** [comment]
Closing due to cf-demo deprecation.
