### ISSUE TITLE
Incorrect styling for gray expandable

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/capital-framework#780]
The styling for our gray expandable variation is incorrect. Additionally, the gray expandable version should be in the variations section within the docs. The white background version should be the default. 

## Current behavior
- Border: No border
- Background (active): Gray 10 (#d2d3d5)
- Background (hover): Gray 20 (#e7e8e9)
- Font-size: 1em
<img width="917" alt="screen shot 2018-03-08 at 12 01 34 pm" src="https://user-images.githubusercontent.com/6887128/37164509-7b2eb710-22c8-11e8-8d7f-683373dc9c68.png">
<img width="907" alt="screen shot 2018-03-08 at 12 01 37 pm" src="https://user-images.githubusercontent.com/6887128/37164510-7b3dfa4a-22c8-11e8-9059-e0046e3909f3.png">

## Expected behavior
- Border: Gray 40 (#b4b5b6)
- Background (active): Gray 5 (#f7f8f9)
- Font-size: 1.125em
- Background (hover): Gray 10 (#e7e8e9)
<img width="914" alt="screen shot 2018-03-08 at 12 16 00 pm" src="https://user-images.githubusercontent.com/6887128/37165687-3b471ed2-22cb-11e8-8afa-3694194c25b2.png">
<img width="909" alt="screen shot 2018-03-08 at 12 15 05 pm" src="https://user-images.githubusercontent.com/6887128/37165696-3f6d3c76-22cb-11e8-9f7e-e27f9ef11f23.png">

## Steps to replicate behavior
1. https://cfpb.github.io/capital-framework/components/cf-expandables

Related content: 
https://cfpb.github.io/design-manual/page-components/expandables.html
https://github.cfpb.gov/flapjack/Modules-V1/wiki/Expandables (DM specs will also need to be updated once we make this fix so please don't reference those specs)

**Comment by anselmbradford** [comment]
Oh yes that looks much better.

**Comment by jimmynotjim** [comment]
Discovered that in practice we don't ever use the hover style change and that it looks really odd in a place like https://www.consumerfinance.gov/about-us/blog/. We should remove that from the spec unless there's a use case someone else is aware of.
