### ISSUE TITLE
Prevent h5 and h6 styles from leaking into .h1-4 classes

### ISSUE THREAD

**Issue by dcmouyard** [cfpb/capital-framework#783]
When a `.h1`, `.h2`, `.h3`, or `.h4` class is added to `<h5>` or `<h6>` they don’t look correct because they get the letter-spacing, text-shadow, and text-transform of h5 or h6.

## Current behavior

- `<h5>` or `<h6>` elements with a `.h1`, `.h2`, `.h3`, or `.h4` class don’t 100% match the look of the corresponding heading element.

## Expected behavior

- `<h5>` or `<h6>` elements with a `.h1`, `.h2`, `.h3`, or `.h4` class should 100% match the look of the corresponding heading element.

## Steps to replicate behavior

1. Add `.h1`, `.h2`, `.h3`, or `.h4` class to an `<h5>` or `<h6>` element.

## Screenshots

__Current__
![image](https://user-images.githubusercontent.com/135259/37425618-5ba60e62-279a-11e8-904c-91e13d4b9591.png)

__Expected__
![image](https://user-images.githubusercontent.com/135259/37425636-66dd2482-279a-11e8-8e77-073fac99e0be.png)

**Comment by dcmouyard** [comment]
Looks like the text-shadow I’m seeing isn’t in the canary branch.

**Comment by cfarm** [comment]
that was removed over in https://github.com/cfpb/capital-framework/pull/778
