### ISSUE TITLE
Remove bower install from grunt-bower-task?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#84]
Per other discussions it might make sense to stop `grunt-bower-task` from running `bower install` and instead let the user do it themselves with Bower.

The benefits (feel free to add more):

- **More intuitive.** Makes explaining the workflow easier since Bower would handle installing and updating dependencies and `grunt-bower-task` would simply be routing the downloaded components to where you need them in your project (obviously somewhat  oversimplified). We already have confusion where users run `bower install` instead of running `grunt vendor` as seen in #14. This change would make the workflow more intuitive since people are more used to running `bower install` first.
- **Stops unnecessary downloads.** Currently updating a component involves updating `bower.json` then running `grunt vendor` which re-downloads all dependencies. If we remove `bower install` from `grunt-bower-task` then updating could be done through Bower and would only update the components that you need. Note that you'd still have to re-run `grunt vendor` to route the files to where you need them in your project though.

To make the change we'd have to tweak the `grunt-bower-task` options to the following:

```js
module.exports = {
  install: {
    options: {
      targetDir: 'src/vendor/',
      install: false,
      copy: true,
      verbose: true,
      cleanTargetDir: true,
      layout: function(type, component) {
        ...
      }
    }
  }
};
```

Changes:

- Changed `install` to `false`
- Added `copy: true`
- Removed `cleanBowerDir: true`. We need to keep the `bower_components` folder because even though updating with Bower will only update what you need, you still need to re-run `grunt-bower-task` and this task re-routes assets for all dependencies.

**Comment by contolini** [comment]
Related to #151.

**Comment by contolini** [comment]
See https://github.com/cfpb/generator-cf/pull/83. @anselmbradford and I have motioned to remove the task altogether.
