### ISSUE TITLE
Expandable Content is within the tabindex

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/capital-framework#860]
# 👋 

Noticed that if there are interactive elements within the expandable content the user can reach them via tab key without being able to see them.

## Current behavior

- Hidden interactive items are reachable via tab key

## Expected behavior

- Hidden interactive items should not be reachable via tab key

## Steps to replicate behavior

1. Put a link in the demo expandable content, tab through the page and watch it highlight the link (and read aloud via VoiceOver) without displaying the link.
1. This bug is currently reproducible on https://www.consumerfinance.gov/about-us/blog/. Tabbing past the expandable header highlights the filter form contents that are hidden.

## Solution

Add `display:'none'` to the expandable content on page load, remove the display prop when state is switched to visible prior to transition, re-add `display:'none'` after the close transition has completed via event listener.

## Screenshots

__Current__

<img width="1345" alt="screen shot 2018-08-30 at 2 10 03 pm" src="https://user-images.githubusercontent.com/1280430/44873682-797df000-ac5e-11e8-9e5e-131bec35e4d2.png">

**Comment by cfarm** [comment]
To replicate this bug I updated the default state expandable on Capital Framework locally to the following markup for the expandable content:

```html
<div class="o-expandable_content">
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing
            elit. Neque ipsa voluptatibus soluta nobis unde quisquam
            temporibus magnam debitis quidem. <a href="#">Ducimus ratione
            corporis nesciunt earum vel est quaerat blanditiis
            dolore ipsa?</a>
        </p>
        <button class="a-btn a-btn__super focus" title="Test button">Button</button>
    </div>
```

I only was able to tab to the button element inside the content div, but not the link element when the expandable is open or closed. When it's open, both should be in the tab order. When it's closed, neither should be.

**Comment by anselmbradford** [comment]
PR --> https://github.com/cfpb/design-system/pull/406
