### ISSUE TITLE
Unexpected SVG icon dependency in cf-forms

### ISSUE THREAD

**Issue by chosak** [cfpb/capital-framework#864]
There are two places in cf-forms LESS files that use a relative path to refer to cf-icons SVG files:

https://github.com/cfpb/capital-framework/blob/5f5727c98b674266d1d9f9413f0b466581e4496b/src/cf-forms/src/atoms/select.less#L67

https://github.com/cfpb/capital-framework/blob/5f5727c98b674266d1d9f9413f0b466581e4496b/src/cf-forms/src/molecules/form-fields.less#L129

The use of relative paths here assumes that compiled CSS will live in a directory with a sibling icons directory, for example `/static/css/compiled.css` next to `/static/icons/down.svg`.

We encountered this (ping @mistergone @schbetsy) when working with the Django [college-costs](https://github.com/cfpb/college-costs) project. This project's content doesn't actually use those SVGs (it's still on the old icon font), but it does pull in the cf-forms LESS into its build.

When running Django locally with `DEBUG=True`, this doesn't cause a problem, as any styles that tried to use these missing icons would have them 404 and not show up. But in production, when using `manage.py collectstatic` with [ManifestStaticFilesStorage](https://docs.djangoproject.com/en/2.1/ref/contrib/staticfiles/#manifeststaticfilesstorage), Django tries to validate that all referenced static assets exist. And because college-costs pulls that LESS into a CSS file that doesn't live right next to `/icons/`, those references make `collectstatic` fail.

The [cf-forms documentation](https://cfpb.github.io/capital-framework/components/cf-forms/) does list cf-icons as a dependency, so it is implied that cf-icons resources might be needed when using cf-forms. But perhaps the need for a sibling `/icons/` folder containing at least the necessary icons could be better documented.

Other thoughts discussed with @Scotchester: replacing those icon references with data URIs (downside: keeping these up to date), using some kind of LESS variable instead of the hardcoded `../icons/`.

**Comment by anselmbradford** [comment]
Fixed in https://github.com/cfpb/capital-framework/pull/934
