### ISSUE TITLE
Select drop-down menu does not use @cf-icon-path variable

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/capital-framework#868]
background-image here https://github.com/cfpb/capital-framework/blob/910723300480e48e2b8b2c5358d330b2311947db/src/cf-forms/src/atoms/select.less#L67 sets path to icon as `'../icons/down.svg'`.

Should that utilize `@cf-icon-path` defined in https://github.com/cfpb/capital-framework/blob/9f50842317473cecfc2bfd25c5bff0eb71d98349/src/cf-icons/usage.md#icon-generation-variables ?

**Comment by jimmynotjim** [comment]
@anselmbradford the icon font was deprecated, the select is using the new svg system, so that var wouldn't work, but there should probably be a new one that points to the new icons.

**Comment by anselmbradford** [comment]
Fixed in https://github.com/cfpb/capital-framework/pull/934
