### ISSUE TITLE
Download compiled source link is broken

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#896]
Short description explaining the high-level reason for the new issue.

## Current behavior

- The link "Download the compiled source" on the homepage does not work.

## Expected behavior

- You should be able to download the compiled source

## Steps to replicate behavior

1. Click the link
2. Get page with error: "Cannot find "/dist/" in capital-framework@8.0.0"

## Screenshots

__Current__

![image](https://user-images.githubusercontent.com/1093373/54133888-4a0a2600-43ed-11e9-8af3-a929e4f92347.png)

**Comment by anselmbradford** [comment]
Looks like the reason the down arrows are missing in selects too https://cfpb.github.io/capital-framework/components/cf-forms/#select-dropdown
