### ISSUE TITLE
Small docs-site tweaks

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#90]
- [ ] Updates for http://cfpb.github.io/capital-framework/#defining-features
 - Add a bullet about responsive
 - Link "accessibility standards" to more information, perhaps link to http://cfpb.github.io/capital-framework/contributing/#accessibility-testing
- [ ] Update the navigation labels to match their corresponding page headings

**Comment by jimmynotjim** [comment]
Docs are completely rebuilt, is this still relevant?

**Comment by Scotchester** [comment]
Obsolete.
