### ISSUE TITLE
Custom demos should expose their notes saying what they're showing

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#97]
For example, https://github.com/cfpb/cf-core/pull/6/files#r16119877.

Seeing the checkbox and radio inputs on the demo page is going to be very confusing if you don't already know that their purpose is to demonstrate that they are NOT accidentally being styled different from the browser default. The note in the comment should be able to be revealed on the demo page.

I'd suggest that if we want to keep the default view on the demo page lean, we add an icon or something that can be hovered/clicked/focused to reveal a comment about that bit of markup.

**Comment by jimmynotjim** [comment]
@Scotchester we've completely rewritten how these are generated, but maybe it's still something we should consider moving to the usage docs? If not, we should close this.

**Comment by Scotchester** [comment]
This doesn't seem applicable anymore.
