### ISSUE TITLE
Delete cf-colors?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/capital-framework#99]
cf-core makes it obsolete so I think we should say bye to it, but let's wait until others have migrated to using cf-core.

**Comment by contolini** [comment]
Let's delete these deprecated repos as part of the 1.0 milestone.

**Comment by contolini** [comment]
I recently discovered `hmda-explorer` is still using cf-colors. Because that project is retired, I don't think it's a good use of our time to transition the codebase. Let's just not delete our deprecated our repos.
